export const lowerExercises = [
  {
    "id": "sentadilla",
    "nombre": "Sentadilla con barra",
    "nombres_alternativos": ["Sentadilla trasera", "Back squat", "Sentadilla libre"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "erectores_espinales", "aductor_mayor", "recto_abdominal"],
    "descripcion": "Ejercicio fundamental de fuerza de tren inferior en el que se flexiona la cadera y rodillas descendiendo con una barra apoyada sobre la espalda.",
    "ejecucion_pasos": [
      "Coloca la barra sobre los trapecios y retírala del soporte con paso firme.",
      "Separa los pies al ancho de los hombros con las puntas ligeramente hacia afuera.",
      "Inhala profundo activando el abdomen para fijar la columna en posición neutra.",
      "Flexiona simultáneamente caderas y rodillas descendiendo de manera controlada.",
      "Baja hasta que la cadera quede a la altura de las rodillas o ligeramente por debajo.",
      "Empuja contra el suelo extendiendo caderas y rodillas para volver a la posición inicial."
    ],
    "equipamiento": ["barra", "soporte_o_rack"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["sentadilla-frontal", "sentadilla-goblet", "sentadilla-sumo", "sentadilla-bulgara", "sentadilla-aerea"],
    "precauciones": ["Requiere controlar la profundidad y mantener una técnica estable evitando que las rodillas colapsen hacia adentro.", "Mantener el torso firme para no redondear la zona lumbar."],
    "tags": ["piernas", "cuadriceps", "gluteos", "fuerza", "hipertrofia", "barra"]
  },
  {
    "id": "sentadilla-frontal",
    "nombre": "Sentadilla frontal",
    "nombres_alternativos": ["Front squat", "Sentadilla por delante"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "recto_abdominal"],
    "musculos_secundarios": ["gluteo_mayor", "erectores_espinales", "deltoides_anterior"],
    "descripcion": "Variante de sentadilla con la barra apoyada sobre los hombros por delante del cuello, exigiendo mayor verticalidad del tronco y activación de cuádriceps y core.",
    "ejecucion_pasos": [
      "Apoya la barra sobre los deltoides anteriores con los codos elevados y paralelos al suelo.",
      "Ubica los pies al ancho de los hombros con puntas algo abiertas.",
      "Mantén el pecho erguido y el abdomen firme.",
      "Desciende flexionando rodillas y caderas con el torso lo más vertical posible.",
      "Alcanza la profundidad deseada sin dejar caer los codos.",
      "Empuja el suelo manteniendo los codos altos para subir."
    ],
    "equipamiento": ["barra", "soporte_o_rack"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["sentadilla", "sentadilla-goblet"],
    "precauciones": ["Requiere adecuada movilidad de muñecas, hombros y tobillos.", "Si bajan los codos, la barra se desestabilizará hacia adelante."],
    "tags": ["cuadriceps", "core", "barra", "fuerza", "olimpico"]
  },
  {
    "id": "sentadilla-goblet",
    "nombre": "Sentadilla goblet",
    "nombres_alternativos": ["Goblet squat", "Sentadilla copa"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["recto_abdominal", "biceps_braquial", "aductor_mayor"],
    "descripcion": "Sentadilla sosteniendo una mancuerna o kettlebell pegada al pecho con ambas manos, ideal para aprender el patrón y mejorar movilidad.",
    "ejecucion_pasos": [
      "Sujeta una mancuerna o kettlebell verticalmente contra el pecho con ambas manos.",
      "Pies separados un poco más allá del ancho de los hombros con puntas hacia afuera.",
      "Inicia el descenso empujando la cadera hacia atrás y abriendo las rodillas en la dirección de los pies.",
      "Baja hasta que los codos queden entre las rodillas manteniendo el pecho alto.",
      "Vuelve a la posición inicial extendiendo con fuerza las piernas."
    ],
    "equipamiento": ["mancuernas", "kettlebell"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["sentadilla", "sentadilla-aerea", "sentadilla-frontal"],
    "precauciones": ["Evitar despegar los talones del suelo al descender.", "Mantener el peso pegado al pecho para no sobrecargar los brazos."],
    "tags": ["cuadriceps", "gluteos", "kettlebell", "mancuernas", "principiante"]
  },
  {
    "id": "sentadilla-sumo",
    "nombre": "Sentadilla sumo",
    "nombres_alternativos": ["Sumo squat", "Sentadilla abierta"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["gluteo_mayor", "aductor_mayor"],
    "musculos_secundarios": ["cuadriceps", "isquiotibiales", "erectores_espinales"],
    "descripcion": "Variante de sentadilla con una postura amplia de pies y rotación externa de caderas que enfatiza aductores y glúteos.",
    "ejecucion_pasos": [
      "Separa los pies notablemente más anchos que los hombros con las puntas apuntando a 45 grados hacia afuera.",
      "Sostén una barra sobre los hombros o una mancuerna pesada entre las piernas.",
      "Desciende flexionando rodillas asegurándote de que sigan la dirección de las puntas de los pies.",
      "Baja manteniendo el tronco lo más erguido posible hasta que los muslos queden paralelos al suelo.",
      "Presiona con los talones y contrae glúteos y aductores para subir."
    ],
    "equipamiento": ["barra", "mancuernas", "kettlebell"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["sentadilla", "peso-muerto-sumo"],
    "precauciones": ["No permitir que las rodillas se cierren hacia adentro durante el ascenso.", "Ajustar la apertura de pies según la movilidad de cadera."],
    "tags": ["gluteos", "aductores", "piernas", "hipertrofia"]
  },
  {
    "id": "sentadilla-bulgara",
    "nombre": "Sentadilla búlgara",
    "nombres_alternativos": ["Bulgarian split squat", "Sentadilla split con pie elevado"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "gluteo_medio", "aductor_mayor"],
    "descripcion": "Ejercicio unilateral de sentadilla con el empeine de la pierna trasera apoyado sobre un banco o soporte elevado.",
    "ejecucion_pasos": [
      "Colócate de espaldas a un banco a un paso de distancia y apoya el empeine de un pie sobre él.",
      "Da un paso adelante con la pierna delantera para mantener una base equilibrada.",
      "Desciende flexionando la rodilla delantera hasta que el muslo quede paralelo al suelo.",
      "La rodilla trasera baja hacia el suelo de forma controlada.",
      "Empuja con el talón de la pierna adelantada para regresar a la posición erguida.",
      "Completa las repeticiones y repite con la otra pierna."
    ],
    "equipamiento": ["banco", "mancuernas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": true,
    "variantes": ["zancadas-estaticas", "sentadilla", "step-up-banco"],
    "precauciones": ["Requiere controlar el equilibrio y la alineación de la rodilla delantera.", "No apoyar excesivo peso en la pierna trasera."],
    "tags": ["gluteos", "cuadriceps", "unilateral", "equilibrio", "mancuernas"]
  },
  {
    "id": "sentadilla-aerea",
    "nombre": "Sentadilla con peso corporal",
    "nombres_alternativos": ["Air squat", "Sentadilla libre sin peso"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "recto_abdominal", "gemelos"],
    "descripcion": "Sentadilla ejecutada exclusivamente con el peso corporal, ideal para calentamiento, resistencia muscular y acondicionamiento.",
    "ejecucion_pasos": [
      "Pies al ancho de los hombros con brazos extendidos al frente para contrapeso.",
      "Flexiona rodillas y caderas llevando el peso hacia los talones y mediopié.",
      "Desciende hasta que los muslos queden al menos paralelos al suelo.",
      "Mantén el pecho alto y la columna neutra.",
      "Empuja el suelo para extender caderas y rodillas por completo."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["sentadilla", "sentadilla-goblet", "sentadilla-pistola"],
    "precauciones": ["Asegurar que los talones no se eleven durante el movimiento."],
    "tags": ["calistenia", "peso_corporal", "principiante", "movilidad"]
  },
  {
    "id": "sentadilla-pistola",
    "nombre": "Sentadilla pistola",
    "nombres_alternativos": ["Pistol squat", "Sentadilla a una pierna"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["gluteo_medio", "isquiotibiales", "recto_abdominal", "gemelos"],
    "descripcion": "Ejercicio avanzado de calistenia donde se realiza una sentadilla completa sobre una sola pierna mientras la otra permanece estirada al frente.",
    "ejecucion_pasos": [
      "Párate sobre una sola pierna y extiende la otra pierna recta hacia adelante.",
      "Extiende los brazos al frente para contrarrestar el peso.",
      "Flexiona la rodilla de apoyo descendiendo lentamente en todo el rango.",
      "Baja hasta que el glúteo casi toque el talón sin que el pie libre toque el suelo.",
      "Presiona con fuerza sobre el pie de apoyo para levantarte a la posición inicial."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": true,
    "variantes": ["sentadilla-aerea", "sentadilla-bulgara"],
    "precauciones": ["Demanda alta flexibilidad en tobillos y caderas.", "Requiere fuerza excéntrica considerable y estabilidad ligamentosa."],
    "tags": ["calistenia", "unilateral", "avanzado", "movilidad", "equilibrio"]
  },
  {
    "id": "prensa-de-piernas",
    "nombre": "Prensa de piernas a 45 grados",
    "nombres_alternativos": ["Leg press", "Prensa inclinada"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "aductor_mayor"],
    "descripcion": "Ejercicio en máquina inclinada donde se empuja una plataforma cargada con los pies manteniendo la espalda protegida y apoyada en el respaldo.",
    "ejecucion_pasos": [
      "Siéntate en la máquina apoyando completamente la espalda y zona lumbar en el respaldo.",
      "Coloca los pies en la plataforma a la anchura de hombros.",
      "Libera los seguros de la máquina empujando ligeramente la plataforma.",
      "Flexiona las rodillas de forma controlada hasta alcanzar un ángulo de 90 grados sin despegar el glúteo.",
      "Empuja la plataforma con los talones y mediopié sin bloquear bruscamente las rodillas al final."
    ],
    "equipamiento": ["maquina"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["sentadilla", "sentadilla-hack"],
    "precauciones": ["Nunca bloquear las rodillas en hiperextensión en la parte alta.", "No despegar la pelvis ni la zona lumbar del respaldo al descender."],
    "tags": ["maquina", "cuadriceps", "gluteos", "hipertrofia", "piernas"]
  },
  {
    "id": "sentadilla-hack",
    "nombre": "Sentadilla hack en máquina",
    "nombres_alternativos": ["Hack squat"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps"],
    "musculos_secundarios": ["gluteo_mayor", "aductor_mayor", "soleo"],
    "descripcion": "Sentadilla guiada en máquina con respaldo inclinado que aísla los cuádriceps reduciendo el requerimiento de estabilización en la zona lumbar.",
    "ejecucion_pasos": [
      "Coloca la espalda contra el respaldo y los hombros bajo las almohadillas acolchadas.",
      "Ubica los pies en la plataforma a la anchura de caderas.",
      "Quita los topes de seguridad extendiendo ligeramente las piernas.",
      "Desciende doblando las rodillas hasta un ángulo de 90 grados manteniendo la espalda fija.",
      "Empuja con los cuádriceps para volver a la posición superior sin trabar rodillas."
    ],
    "equipamiento": ["maquina"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["prensa-de-piernas", "sentadilla"],
    "precauciones": ["Mantener la espalda pegada al soporte en todo momento.", "No despegar los talones de la plataforma."],
    "tags": ["maquina", "cuadriceps", "hipertrofia", "fuerza"]
  },
  {
    "id": "sentadilla-isometrica-pared",
    "nombre": "Sentadilla isométrica en pared",
    "nombres_alternativos": ["Wall sit", "Silla estática"],
    "familia": "sentadilla",
    "patron_movimiento": "sentadilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps"],
    "musculos_secundarios": ["gluteo_mayor", "isquiotibiales", "recto_abdominal"],
    "descripcion": "Mantenimiento estático de la posición de sentadilla apoyando la espalda contra la pared, excelente para resistencia y salud articular.",
    "ejecucion_pasos": [
      "Apoya la espalda completamente plana contra una pared.",
      "Camina con los pies hacia adelante y deslízate hacia abajo hasta que los muslos queden paralelos al suelo.",
      "Las rodillas deben quedar directamente sobre los tobillos formando un ángulo de 90 grados.",
      "Mantén la posición el tiempo prescrito respirando de manera fluida.",
      "Apóyate en la pared para reincorporarte con cuidado."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["sentadilla-aerea"],
    "precauciones": ["No dejar que las rodillas sobrepasen excesivamente la línea de las puntas.", "Mantener la espalda firmemente apoyada."],
    "tags": ["isometrico", "resistencia", "peso_corporal", "salud_articular"]
  },
  {
    "id": "peso-muerto-convencional",
    "nombre": "Peso muerto con barra",
    "nombres_alternativos": ["Deadlift", "Peso muerto convencional"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "isquiotibiales", "erectores_espinales"],
    "musculos_secundarios": ["dorsal_ancho", "trapecio", "cuadriceps", "antebrazos", "recto_abdominal"],
    "descripcion": "Levantamiento básico desde el suelo mediante bisagra de cadera donde se levanta una barra hasta la extensión completa de caderas.",
    "ejecucion_pasos": [
      "Coloca los pies debajo de la barra a la anchura de las caderas con la barra sobre la mitad del pie.",
      "Inclínate flexionando caderas y sujeta la barra por fuera de las rodillas.",
      "Baja la cadera, saca pecho y activa dorsales fijando la espalda en posición neutra.",
      "Inhala, aprieta el abdomen y empuja el suelo con las piernas manteniendo la barra pegada al cuerpo.",
      "Extiende caderas y rodillas simultáneamente hasta quedar completamente erguido.",
      "Desciende controlando la barra de regreso al suelo con bisagra de cadera."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["peso-muerto-sumo", "peso-muerto-rumano-barra"],
    "precauciones": ["Mantener la barra rozando las espinillas y muslos para minimizar el brazo de palanca lumbar.", "No hiperextender la espalda en el bloqueo final."],
    "tags": ["fuerza", "cadena_posterior", "barra", "basico", "gluteos"]
  },
  {
    "id": "peso-muerto-sumo",
    "nombre": "Peso muerto sumo",
    "nombres_alternativos": ["Sumo deadlift"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "aductor_mayor", "cuadriceps"],
    "musculos_secundarios": ["isquiotibiales", "erectores_espinales", "trapecio", "antebrazos"],
    "descripcion": "Variante de peso muerto con pies muy separados y agarre estrecho por dentro de las piernas, permitiendo un torso más vertical.",
    "ejecucion_pasos": [
      "Adopta una postura ancha con pies cerca de los discos y puntas orientadas hacia afuera.",
      "Flexiona rodillas y caderas manteniendo el torso vertical y sujeta la barra por dentro de las piernas.",
      "Pega las espinillas a la barra y abre las rodillas hacia afuera.",
      "Empuja el suelo extendiendo piernas y llevando la pelvis hacia la barra.",
      "Bloquea caderas y rodillas sin tirar con la zona lumbar."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["peso-muerto-convencional", "sentadilla-sumo"],
    "precauciones": ["Requiere buena movilidad de aductores y rotación externa de caderas.", "Comenzar con cargas moderadas para adaptar los aductores."],
    "tags": ["fuerza", "gluteos", "aductores", "barra", "powerlifting"]
  },
  {
    "id": "peso-muerto-rumano-barra",
    "nombre": "Peso muerto rumano con barra",
    "nombres_alternativos": ["Romanian deadlift", "RDL con barra"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales", "gluteo_mayor"],
    "musculos_secundarios": ["erectores_espinales", "dorsal_ancho", "antebrazos"],
    "descripcion": "Ejercicio de bisagra de cadera donde se desciende la barra hasta debajo de las rodillas con mínima flexión de rodilla, enfatizando isquios y glúteos.",
    "ejecucion_pasos": [
      "Inicia de pie sujetando la barra a la anchura de hombros con las rodillas ligeramente desbloqueadas.",
      "Lleva la cadera hacia atrás como si quisieras tocar una pared con los glúteos.",
      "Baja la barra rozando los muslos manteniendo la espalda totalmente recta.",
      "Detén el descenso cuando sientas el estiramiento máximo de los isquiotibiales (normalmente bajo la rodilla).",
      "Empuja las caderas hacia adelante contrayendo glúteos para volver a ponerte de pie."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["peso-muerto-rumano-mancuernas", "peso-muerto-convencional", "buenos-dias"],
    "precauciones": ["No transformar el movimiento en una sentadilla flexionando de más las rodillas.", "No redondear la espalda para intentar bajar más."],
    "tags": ["isquiotibiales", "gluteos", "cadena_posterior", "hipertrofia", "barra"]
  },
  {
    "id": "peso-muerto-rumano-mancuernas",
    "nombre": "Peso muerto rumano con mancuernas",
    "nombres_alternativos": ["Dumbbell RDL", "RDL con mancuernas"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales", "gluteo_mayor"],
    "musculos_secundarios": ["erectores_espinales", "gluteo_medio", "antebrazos"],
    "descripcion": "Variante del peso muerto rumano que utiliza mancuernas, permitiendo un recorrido más natural y cómodo para los brazos.",
    "ejecucion_pasos": [
      "Sujeta una mancuerna en cada mano frente a los muslos con palmas mirando hacia el cuerpo.",
      "Pies al ancho de caderas con rodillas semiflexionadas fijas.",
      "Desplaza las caderas hacia atrás deslizando las mancuernas cerca de las piernas.",
      "Baja hasta el punto de máximo estiramiento de isquiotibiales sin encorvar la espalda.",
      "Contrae glúteos y extiende la cadera para retornar arriba."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["peso-muerto-rumano-barra", "peso-muerto-unilateral"],
    "precauciones": ["Mantener las mancuernas próximas a las piernas para proteger la espalda baja."],
    "tags": ["mancuernas", "isquiotibiales", "gluteos", "cadena_posterior"]
  },
  {
    "id": "peso-muerto-unilateral",
    "nombre": "Peso muerto rumano unilateral",
    "nombres_alternativos": ["Single leg deadlift", "Peso muerto a una pierna"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales", "gluteo_mayor", "gluteo_medio"],
    "musculos_secundarios": ["erectores_espinales", "recto_abdominal", "gemelos"],
    "descripcion": "Bisagra de cadera realizada sobre una pierna mientras la otra se extiende hacia atrás, desarrollando equilibrio, fuerza y estabilidad de cadera.",
    "ejecucion_pasos": [
      "Párate sobre una pierna con una mancuerna o kettlebell en la mano contraria o ambas.",
      "Mantén la rodilla de apoyo ligeramente desbloqueada.",
      "Inclina el torso hacia adelante empujando la pierna libre recta hacia atrás en una línea recta.",
      "Baja el peso hacia la espinilla manteniendo la pelvis nivelada y paralela al suelo.",
      "Empuja con el talón de apoyo y extiende la cadera para volver a la posición inicial."
    ],
    "equipamiento": ["mancuernas", "kettlebell", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": true,
    "variantes": ["peso-muerto-rumano-mancuernas"],
    "precauciones": ["Evitar rotar o abrir la cadera hacia el lateral de la pierna levantada.", "Asegurar un control lento y deliberado."],
    "tags": ["unilateral", "equilibrio", "isquiotibiales", "gluteos"]
  },
  {
    "id": "hip-thrust-barra",
    "nombre": "Hip thrust con barra",
    "nombres_alternativos": ["Empuje de cadera con barra", "Barbell hip thrust"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "extension_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "cuadriceps", "erectores_espinales"],
    "descripcion": "Ejercicio de máxima activación y sobrecarga del glúteo mayor mediante extensión horizontal de cadera con apoyo escapular en banco.",
    "ejecucion_pasos": [
      "Siéntate en el suelo con la parte media de la espalda apoyada contra el borde de un banco estable.",
      "Coloca una barra acolchada sobre el pliegue de la cadera.",
      "Apoya las plantas de los pies firmes en el suelo al ancho de hombros con rodillas a 90 grados en la parte alta.",
      "Empuja a través de los talones y extiende las caderas elevando la barra hasta que los muslos y el torso queden alineados.",
      "Aprieta fuerte los glúteos durante un segundo arriba sin arquear la columna lumbar.",
      "Desciende la cadera controladamente sin que los glúteos descansen en el suelo."
    ],
    "equipamiento": ["barra", "banco", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["hip-thrust-unilateral", "puente-de-gluteos"],
    "precauciones": ["Usar siempre almohadilla protectora para la barra.", "Mantener la barbilla pegada al pecho mirando al frente para evitar hiperextensión lumbar."],
    "tags": ["gluteos", "fuerza", "hipertrofia", "barra", "cadera"]
  },
  {
    "id": "hip-thrust-unilateral",
    "nombre": "Hip thrust a una pierna",
    "nombres_alternativos": ["Single leg hip thrust"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "extension_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["gluteo_mayor", "gluteo_medio"],
    "musculos_secundarios": ["isquiotibiales", "cuadriceps", "recto_abdominal"],
    "descripcion": "Variante unilateral del hip thrust que corrige asimetrías de fuerza en los glúteos y mejora la estabilidad lumbopélvica.",
    "ejecucion_pasos": [
      "Apoya las escápulas en un banco con una sola pierna apoyada en el suelo y la otra flexionada en el aire.",
      "Empuja con el talón de apoyo elevando la pelvis hasta alinearla con el muslo y torso.",
      "Contrae el glúteo en la cima manteniendo la pelvis horizontal.",
      "Baja lentamente y repite antes de cambiar de pierna."
    ],
    "equipamiento": ["banco", "mancuernas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": true,
    "variantes": ["hip-thrust-barra", "puente-de-gluteos"],
    "precauciones": ["Evitar que la pelvis caiga hacia el lado de la pierna libre."],
    "tags": ["gluteos", "unilateral", "estabilidad", "hipertrofia"]
  },
  {
    "id": "puente-de-gluteos",
    "nombre": "Puente de glúteos en suelo",
    "nombres_alternativos": ["Glute bridge"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "extension_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "erectores_espinales"],
    "descripcion": "Ejercicio en el suelo para activación y fortalecimiento de glúteos mediante elevación de pelvis.",
    "ejecucion_pasos": [
      "Acuéstate boca arriba en el suelo con las rodillas dobladas y pies apoyados cerca de los glúteos.",
      "Brazos estirados a los lados en el suelo.",
      "Presiona los talones y eleva la cadera contrayendo los glúteos.",
      "Forma una línea recta desde las rodillas hasta los hombros.",
      "Mantén un segundo arriba y baja despacio sin apoyar del todo."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["hip-thrust-barra", "hip-thrust-unilateral"],
    "precauciones": ["No arquear excesivamente la espalda baja al subir; la fuerza proviene del glúteo."],
    "tags": ["gluteos", "principiante", "peso_corporal", "activacion"]
  },
  {
    "id": "buenos-dias",
    "nombre": "Buenos días con barra",
    "nombres_alternativos": ["Good mornings"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "bisagra_de_cadera",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales", "erectores_espinales"],
    "musculos_secundarios": ["gluteo_mayor", "dorsal_ancho"],
    "descripcion": "Movimiento de bisagra de cadera con la barra cargada en la espalda alta, enfocado en isquiosurales y fortalecimiento lumbar.",
    "ejecucion_pasos": [
      "Coloca la barra sobre la espalda alta igual que en una sentadilla.",
      "Pies al ancho de caderas con rodillas con una ligera flexión constante.",
      "Empuja las caderas hacia atrás inclinando el torso hacia adelante.",
      "Baja el pecho hasta casi quedar paralelo al suelo sin curvar la espalda.",
      "Contrae isquiotibiales y glúteos para erguir el torso a la posición inicial."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["peso-muerto-rumano-barra"],
    "precauciones": ["Requiere excelente control lumbopélvico. Utilizar cargas conservadoras."],
    "tags": ["isquiotibiales", "lumbar", "cadena_posterior", "barra"]
  },
  {
    "id": "kettlebell-swing",
    "nombre": "Kettlebell swing",
    "nombres_alternativos": ["Balanceo con pesa rusa", "Russian kettlebell swing"],
    "familia": "bisagra_de_cadera",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "isquiotibiales"],
    "musculos_secundarios": ["erectores_espinales", "recto_abdominal", "deltoides_anterior", "antebrazos"],
    "descripcion": "Ejercicio balístico y dinámico de bisagra de cadera donde se propulsa una pesa rusa a la altura del pecho usando la potencia de glúteos e isquios.",
    "ejecucion_pasos": [
      "Pies un poco más anchos que los hombros con la pesa en el suelo frente a ti.",
      "Inclínate en bisagra de cadera y toma la pesa con ambas manos.",
      "Balancea la pesa hacia atrás entre las piernas flexionando caderas.",
      "Extiende caderas de forma explosiva contrayendo glúteos para impulsar la pesa al frente a la altura del pecho.",
      "Permite que la pesa caiga por gravedad acompañando el movimiento hacia atrás en bisagra para la siguiente repetición."
    ],
    "equipamiento": ["kettlebell"],
    "tipo": "potencia",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["peso-muerto-convencional"],
    "precauciones": ["El movimiento debe ser un empuje de cadera, no una sentadilla ni una elevación frontal con los brazos."],
    "tags": ["kettlebell", "potencia", "gluteos", "cardiovascular", "acondicionamiento"]
  },
  {
    "id": "zancadas-caminando",
    "nombre": "Zancadas caminando",
    "nombres_alternativos": ["Walking lunges", "Pasos de tijera"],
    "familia": "zancada",
    "patron_movimiento": "zancada",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "gluteo_medio", "gemelos"],
    "descripcion": "Zancadas continuas avanzando hacia adelante que desafían la fuerza unilateral, la estabilidad y la resistencia de piernas y glúteos.",
    "ejecucion_pasos": [
      "De pie con mancuernas a los costados o peso corporal.",
      "Da un paso amplio hacia adelante flexionando ambas rodillas a 90 grados.",
      "La rodilla trasera roza suavemente el suelo sin golpearlo.",
      "Empuja con el talón delantero y avanza la pierna trasera directamente al siguiente paso.",
      "Continúa alternando pasos con fluidez manteniendo el tronco erguido."
    ],
    "equipamiento": ["mancuernas", "peso_corporal", "barra"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": true,
    "variantes": ["zancadas-estaticas", "zancadas-inversas", "sentadilla-bulgara"],
    "precauciones": ["Mantener la rodilla delantera alineada con el segundo dedo del pie.", "No inclinar excesivamente el torso hacia adelante."],
    "tags": ["zancadas", "gluteos", "cuadriceps", "unilateral", "piernas"]
  },
  {
    "id": "zancadas-estaticas",
    "nombre": "Zancadas estáticas",
    "nombres_alternativos": ["Split squat", "Zancadas en el sitio"],
    "familia": "zancada",
    "patron_movimiento": "zancada",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "gluteo_medio"],
    "descripcion": "Zancada fija en el lugar donde se sube y baja verticalmente sin desplazar los pies.",
    "ejecucion_pasos": [
      "Coloca un pie adelantado y otro retrasado apoyado en metatarsos.",
      "Desciende en línea recta doblando ambas rodillas hasta los 90 grados.",
      "Extiende las piernas para volver arriba sin mover los pies del sitio.",
      "Completa las repeticiones de un lado y luego cambia al otro."
    ],
    "equipamiento": ["mancuernas", "peso_corporal", "barra"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["zancadas-caminando", "zancadas-inversas", "sentadilla-bulgara"],
    "precauciones": ["Distribuir el peso equilibradamente sin sobrecargar la punta del pie."],
    "tags": ["piernas", "gluteos", "cuadriceps", "principiante"]
  },
  {
    "id": "zancadas-inversas",
    "nombre": "Zancadas inversas",
    "nombres_alternativos": ["Reverse lunges", "Zancadas hacia atrás"],
    "familia": "zancada",
    "patron_movimiento": "zancada",
    "zona": "inferior",
    "musculos_principales": ["gluteo_mayor", "cuadriceps"],
    "musculos_secundarios": ["isquiotibiales", "gluteo_medio"],
    "descripcion": "Zancada dando el paso hacia atrás, variante más amigable con la articulación de la rodilla y con mayor estímulo en glúteos.",
    "ejecucion_pasos": [
      "Comienza de pie con los pies juntos.",
      "Da un paso hacia atrás con una pierna y flexiona ambas rodillas a 90 grados.",
      "La tibia de la pierna delantera se mantiene casi vertical.",
      "Empuja fuertemente con el talón delantero para regresar a la posición inicial erguida.",
      "Alterna piernas o completa una serie por pierna."
    ],
    "equipamiento": ["mancuernas", "peso_corporal", "kettlebell"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["zancadas-estaticas", "zancadas-caminando"],
    "precauciones": ["Controlar el aterrizaje del pie trasero para no perder el equilibrio."],
    "tags": ["gluteos", "cuadriceps", "rodilla_amigable", "unilateral"]
  },
  {
    "id": "step-up-banco",
    "nombre": "Subidas al banco",
    "nombres_alternativos": ["Step ups", "Subidas al cajón"],
    "familia": "zancada",
    "patron_movimiento": "locomocion",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["gluteo_medio", "gemelos", "isquiotibiales"],
    "descripcion": "Ascenso a un banco o cajón apoyando un pie e impulsando el cuerpo únicamente con la pierna de arriba.",
    "ejecucion_pasos": [
      "Coloca un pie completo sobre un banco o cajón a la altura de la rodilla.",
      "Transfiere el peso hacia el talón de la pierna apoyada arriba.",
      "Presiona y elévate extendiendo la pierna sin impulsarte con el pie del suelo.",
      "Termina de pie sobre el banco y desciende de manera lenta y controlada."
    ],
    "equipamiento": ["banco", "cajon", "mancuernas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["sentadilla-bulgara", "zancadas-caminando"],
    "precauciones": ["Evitar rebotar con el pie inferior; el trabajo debe realizarlo la pierna superior."],
    "tags": ["gluteos", "cuadriceps", "unilateral", "funcional"]
  },
  {
    "id": "extension-cuadriceps-maquina",
    "nombre": "Extensión de cuádriceps en máquina",
    "nombres_alternativos": ["Leg extension", "Sillón de cuadriceps"],
    "familia": "extension_de_piernas",
    "patron_movimiento": "extension_de_rodilla",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps"],
    "musculos_secundarios": [],
    "descripcion": "Ejercicio de aislamiento sentado en máquina donde se extienden las rodillas contra una almohadilla acolchada para aislar los cuatro vientres del cuádriceps.",
    "ejecucion_pasos": [
      "Ajusta el respaldo para que el eje de giro de la máquina coincida con la articulación de tus rodillas.",
      "Coloca la almohadilla sobre la parte baja de las espinillas justo encima de los tobillos.",
      "Sujeta los agarres laterales y extiende las piernas hasta que queden rectas.",
      "Aguanta un segundo en contracción máxima.",
      "Desciende el peso de forma controlada sin que las placas choquen bruscamente."
    ],
    "equipamiento": ["maquina"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["sentadilla-hack", "prensa-de-piernas"],
    "precauciones": ["Evitar movimientos bruscos o patadas; mantener tensión continua."],
    "tags": ["cuadriceps", "aislamiento", "maquina", "hipertrofia"]
  },
  {
    "id": "curl-femoral-tumbado",
    "nombre": "Curl femoral tumbado",
    "nombres_alternativos": ["Lying leg curl", "Curl de piernas acostado"],
    "familia": "flexion_de_piernas",
    "patron_movimiento": "flexion_de_rodilla",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales"],
    "musculos_secundarios": ["gemelos"],
    "descripcion": "Ejercicio de aislamiento boca abajo en máquina que trabaja la flexión de rodilla focalizando en los isquiosurales.",
    "ejecucion_pasos": [
      "Túmbate boca abajo colocando la almohadilla detrás de los tobillos.",
      "Asegúrate de que las rodillas queden justo por fuera del borde del banco.",
      "Sujeta los mangos y contrae los isquiotibiales flexionando los talones hacia los glúteos.",
      "Mantén la pelvis pegada al banco en todo momento.",
      "Extiende lentamente las piernas volviendo a la posición inicial."
    ],
    "equipamiento": ["maquina"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["curl-femoral-sentado", "curl-nordico"],
    "precauciones": ["No levantar la cadera del banco durante la contracción máxima."],
    "tags": ["isquiotibiales", "aislamiento", "maquina", "cadena_posterior"]
  },
  {
    "id": "curl-femoral-sentado",
    "nombre": "Curl femoral sentado",
    "nombres_alternativos": ["Seated leg curl"],
    "familia": "flexion_de_piernas",
    "patron_movimiento": "flexion_de_rodilla",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales"],
    "musculos_secundarios": ["gemelos"],
    "descripcion": "Aislamiento de isquiosurales en posición sentada, lo que coloca la cadera en flexión y genera mayor elongación y tensión muscular.",
    "ejecucion_pasos": [
      "Siéntate y ajusta el soporte superior firme sobre los muslos para evitar que se eleven.",
      "Coloca la almohadilla trasera contra los tendones de Aquiles.",
      "Flexiona las piernas hacia abajo y atrás llevando los talones debajo del asiento.",
      "Aprieta en la posición más baja y regresa frenando la subida."
    ],
    "equipamiento": ["maquina"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["curl-femoral-tumbado", "curl-nordico"],
    "precauciones": ["Fijar bien el muslo para aislar verdaderamente los isquiosurales."],
    "tags": ["isquiotibiales", "maquina", "aislamiento", "hipertrofia"]
  },
  {
    "id": "curl-nordico",
    "nombre": "Curl nórdico",
    "nombres_alternativos": ["Nordic hamstring curl", "Curl ruso"],
    "familia": "flexion_de_piernas",
    "patron_movimiento": "flexion_de_rodilla",
    "zona": "inferior",
    "musculos_principales": ["isquiotibiales"],
    "musculos_secundarios": ["gluteo_mayor", "erectores_espinales", "gemelos"],
    "descripcion": "Exigente ejercicio excéntrico para isquiosurales donde de rodillas se desciende el torso hacia adelante controlando con la fuerza de la parte posterior del muslo.",
    "ejecucion_pasos": [
      "Ponte de rodillas sobre una superficie acolchada con los tobillos firmemente anclados.",
      "Mantén las caderas en extensión completa formando una línea recta rodilla-cadera-hombro.",
      "Desciende el cuerpo hacia adelante frenando la caída tan lento como sea posible con los isquiosurales.",
      "Cuando no puedas sostenerlo más, apoya las manos en el suelo en flexión para amortiguar.",
      "Empuja ligeramente con las manos para volver a iniciar."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["curl-femoral-tumbado", "peso-muerto-rumano-barra"],
    "precauciones": ["Gran exigencia excéntrica; requiere progresión con bandas elásticas o rango parcial al inicio."],
    "tags": ["isquiotibiales", "calistenia", "prevencion_lesiones", "excentrico", "avanzado"]
  },
  {
    "id": "elevacion-talones-de-pie",
    "nombre": "Elevación de talones de pie",
    "nombres_alternativos": ["Calf raise de pie", "Elevación de pantorrillas"],
    "familia": "elevacion",
    "patron_movimiento": "extension_de_tobillo",
    "zona": "inferior",
    "musculos_principales": ["gemelos"],
    "musculos_secundarios": ["soleo"],
    "descripcion": "Ejercicio para el desarrollo de los gemelos (gastrocnemios) elevando los talones sobre un escalón o máquina con rodillas extendidas.",
    "ejecucion_pasos": [
      "Apoya los metatarsos en el borde de un escalón o plataforma con los talones libres.",
      "Baja los talones por debajo del nivel del escalón para estirar completamente la pantorrilla.",
      "Empuja fuerte con las puntas de los pies elevándote lo más alto posible.",
      "Aguanta un segundo arriba y baja lentamente."
    ],
    "equipamiento": ["maquina", "mancuernas", "peso_corporal"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["elevacion-talones-sentado"],
    "precauciones": ["Realizar una pausa abajo para eliminar el rebote elástico del tendón de Aquiles."],
    "tags": ["gemelos", "pantorrillas", "aislamiento", "tobillo"]
  },
  {
    "id": "elevacion-talones-sentado",
    "nombre": "Elevación de talones sentado",
    "nombres_alternativos": ["Seated calf raise"],
    "familia": "elevacion",
    "patron_movimiento": "extension_de_tobillo",
    "zona": "inferior",
    "musculos_principales": ["soleo"],
    "musculos_secundarios": ["gemelos"],
    "descripcion": "Elevación de talones con las rodillas a 90 grados, lo que desactiva en gran parte los gastrocnemios para aislar el sóleo.",
    "ejecucion_pasos": [
      "Siéntate en la máquina de gemelos con los muslos bajo el acolchado.",
      "Apoya las puntas de los pies en el soporte dejando colgar los talones.",
      "Baja los talones en rango completo.",
      "Empuja hacia arriba hasta la contracción máxima y haz una pausa.",
      "Desciende controladamente."
    ],
    "equipamiento": ["maquina"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["elevacion-talones-de-pie"],
    "precauciones": ["No rebotar; controlar el rango completo."],
    "tags": ["soleo", "pantorrillas", "maquina", "aislamiento"]
  }
];
