export const coreCardioMovExercises = [
  {
    "id": "plancha-abdominal-frontal",
    "nombre": "Plancha abdominal frontal",
    "nombres_alternativos": ["Plank", "Plancha isométrica", "Plancha prono"],
    "familia": "core",
    "patron_movimiento": "anti_extension",
    "zona": "core",
    "musculos_principales": ["recto_abdominal", "transverso_abdominal"],
    "musculos_secundarios": ["oblicuo_externo", "gluteo_mayor", "deltoides_anterior"],
    "descripcion": "Mantenimiento isométrico del cuerpo en línea recta apoyado sobre los antebrazos y las puntas de los pies para resistir la extensión lumbar.",
    "ejecucion_pasos": [
      "Apoya los antebrazos en el suelo separados al ancho de hombros con los codos debajo de los hombros.",
      "Extiende las piernas hacia atrás apoyándote en las puntas de los pies.",
      "Activa glúteos, cuádriceps y abdomen para alinear hombros, caderas y talones.",
      "Empuja el suelo con los codos separando las escápulas activamente.",
      "Mantén la posición respirando de manera fluida y rítmica sin arquear la espalda."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["plancha-lateral", "rueda-abdominal", "hollow-body-hold"],
    "precauciones": ["No permitir que la pelvis caiga hacia el suelo ni subir los glúteos en exceso."],
    "tags": ["core", "abdomen", "isometrico", "peso_corporal", "estabilidad"]
  },
  {
    "id": "plancha-lateral",
    "nombre": "Plancha lateral",
    "nombres_alternativos": ["Side plank"],
    "familia": "core",
    "patron_movimiento": "anti_flexion_lateral",
    "zona": "core",
    "musculos_principales": ["oblicuo_externo", "oblicuo_interno", "gluteo_medio"],
    "musculos_secundarios": ["recto_abdominal", "transverso_abdominal", "deltoides_lateral"],
    "descripcion": "Sostén isométrico apoyado de costado sobre un antebrazo para fortalecer los oblicuos y estabilizadores laterales de la cadera.",
    "ejecucion_pasos": [
      "Acuéstate de lado apoyando el antebrazo bajo el hombro.",
      "Apila los pies uno sobre otro o coloca el superior justo delante.",
      "Eleva la cadera del suelo formando una línea diagonal desde la cabeza a los pies.",
      "Coloca el brazo libre estirado hacia el techo o en la cadera.",
      "Mantén la cadera elevada y firme durante el tiempo asignado."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["plancha-abdominal-frontal", "press-pallof"],
    "precauciones": ["Evitar que la cadera caiga o rote hacia adelante."],
    "tags": ["core", "oblicuos", "estabilidad", "unilateral"]
  },
  {
    "id": "rueda-abdominal",
    "nombre": "Rueda abdominal desde rodillas",
    "nombres_alternativos": ["Ab wheel rollout", "Despliegue con rueda"],
    "familia": "core",
    "patron_movimiento": "anti_extension",
    "zona": "core",
    "musculos_principales": ["recto_abdominal", "transverso_abdominal"],
    "musculos_secundarios": ["dorsal_ancho", "deltoides_anterior", "triceps_braquial"],
    "descripcion": "Intenso ejercicio de anti-extensión de columna rodando una rueda hacia adelante sobre las rodillas y retrayendo con la fuerza del core.",
    "ejecucion_pasos": [
      "Arrodíllate sobre una colchoneta sujetando la rueda con ambas manos debajo de los hombros.",
      "Bascula la pelvis en retroversión redondeando levemente la zona lumbar para protegerla.",
      "Rueda hacia adelante extendiendo caderas y brazos lentamente de forma controlada.",
      "Avanza hasta el punto máximo donde puedas mantener el abdomen tenso sin arquear la espalda.",
      "Tira con el abdomen y dorsales para regresar a la posición inicial."
    ],
    "equipamiento": ["rueda_abdominal", "esterilla"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["plancha-abdominal-frontal", "hollow-body-hold", "dead-bug"],
    "precauciones": ["Detener inmediatamente si se siente pellizco o carga en la zona lumbar baja."],
    "tags": ["core", "anti_extension", "abdominales", "avanzado"]
  },
  {
    "id": "hollow-body-hold",
    "nombre": "Hollow body hold",
    "nombres_alternativos": ["Posición de canoa", "Hollow body"],
    "familia": "core",
    "patron_movimiento": "anti_extension",
    "zona": "core",
    "musculos_principales": ["recto_abdominal", "transverso_abdominal"],
    "musculos_secundarios": ["iliopsoas", "cuadriceps"],
    "descripcion": "Postura gimnástica fundamental donde se comprime la espalda baja contra el suelo manteniendo brazos y piernas suspendidos en el aire.",
    "ejecucion_pasos": [
      "Acuéstate boca arriba y aplasta la zona lumbar completamente contra el suelo sin dejar hueco.",
      "Extiende los brazos por detrás de la cabeza pegados a las orejas.",
      "Eleva hombros, escápulas y piernas a unos centímetros del piso formando una forma de barco cóncavo.",
      "Respira corto manteniendo la tensión abdominal máxima en todo momento."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["plancha-abdominal-frontal", "dead-bug"],
    "precauciones": ["Si la espalda baja se despega del suelo, flexionar ligeramente las rodillas o elevar más las piernas."],
    "tags": ["calistenia", "gimnasia", "core", "peso_corporal"]
  },
  {
    "id": "elevacion-piernas-colgado",
    "nombre": "Elevación de piernas colgado",
    "nombres_alternativos": ["Hanging leg raise", "Toes to bar"],
    "familia": "core",
    "patron_movimiento": "flexion_de_cadera",
    "zona": "core",
    "musculos_principales": ["recto_abdominal", "iliopsoas"],
    "musculos_secundarios": ["oblicuo_externo", "antebrazos", "dorsal_ancho"],
    "descripcion": "Elevación de piernas suspendido de una barra de dominadas flexionando la cadera y enrollando la pelvis hacia el pecho.",
    "ejecucion_pasos": [
      "Cuélgate de una barra con brazos extendidos y cuerpo quieto.",
      "Sin balancearte, contrae el abdomen y eleva las piernas rectas hasta que queden paralelas al suelo o toquen la barra.",
      "Bascula la pelvis hacia arriba para enfatizar los abdominales sobre los flexores de cadera.",
      "Baja las piernas lentamente resistiendo la caída."
    ],
    "equipamiento": ["barra_de_dominadas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["crunch-abdominal-suelo", "crunch-en-polea-alta"],
    "precauciones": ["Evitar el balanceo con inercia para asegurar que el trabajo lo realice el abdomen."],
    "tags": ["core", "calistenia", "abdominales", "barra_de_dominadas"]
  },
  {
    "id": "crunch-abdominal-suelo",
    "nombre": "Crunch abdominal en suelo",
    "nombres_alternativos": ["Abdominal clásico", "Encogimiento abdominal"],
    "familia": "core",
    "patron_movimiento": "flexion_de_tronco",
    "zona": "core",
    "musculos_principales": ["recto_abdominal"],
    "musculos_secundarios": ["oblicuo_externo"],
    "descripcion": "Flexión aislada de la columna torácica acercando las costillas hacia la pelvis despegando únicamente las escápulas del suelo.",
    "ejecucion_pasos": [
      "Túmbate boca arriba con rodillas dobladas y plantas apoyadas en el suelo.",
      "Coloca las puntas de los dedos detrás de las orejas sin tirar del cuello.",
      "Exhala y flexiona el tronco despegando las escápulas unos centímetros del suelo.",
      "Aprieta el abdomen un segundo en la cima.",
      "Desciende despacio hasta apoyar las escápulas."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["crunch-en-polea-alta", "elevacion-piernas-colgado"],
    "precauciones": ["No tirar de la cabeza con las manos para no tensar las cervicales."],
    "tags": ["core", "abdomen", "principiante", "peso_corporal"]
  },
  {
    "id": "crunch-en-polea-alta",
    "nombre": "Crunch en polea alta de rodillas",
    "nombres_alternativos": ["Cable crunch", "Encogimiento en polea"],
    "familia": "core",
    "patron_movimiento": "flexion_de_tronco",
    "zona": "core",
    "musculos_principales": ["recto_abdominal"],
    "musculos_secundarios": ["oblicuo_externo"],
    "descripcion": "Encogimiento de tronco de rodillas sujetando una cuerda conectada a la polea alta para permitir sobrecarga progresiva en los abdominales.",
    "ejecucion_pasos": [
      "Arrodíllate frente a la torre de poleas y coloca las manos con la cuerda a los lados de la cabeza.",
      "Mantén las caderas fijas y encorva la espalda llevando los codos hacia las rodillas.",
      "Contrae intensamente los abdominales abajo.",
      "Regresa controlando el peso sin extender la cadera."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["crunch-abdominal-suelo"],
    "precauciones": ["El movimiento debe originarse en la columna, no flexionando las caderas."],
    "tags": ["polea", "core", "hipertrofia", "abdominales"]
  },
  {
    "id": "dead-bug",
    "nombre": "Dead bug",
    "nombres_alternativos": ["Bicho muerto"],
    "familia": "core",
    "patron_movimiento": "anti_extension",
    "zona": "core",
    "musculos_principales": ["transverso_abdominal", "recto_abdominal"],
    "musculos_secundarios": ["oblicuo_interno", "iliopsoas"],
    "descripcion": "Ejercicio de control motor y disociación lumbo-pélvica extendiendo alternadamente brazo y pierna opuesta sin despegar la zona lumbar.",
    "ejecucion_pasos": [
      "Túmbate boca arriba con brazos extendidos hacia el techo y rodillas flexionadas a 90 grados en el aire.",
      "Pega la zona lumbar firmemente contra el suelo.",
      "Extiende simultáneamente el brazo derecho hacia atrás y la pierna izquierda hacia adelante hasta rozar el suelo.",
      "Vuelve al centro y repite con el brazo izquierdo y pierna derecha."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["bird-dog", "plancha-abdominal-frontal"],
    "precauciones": ["Si la espalda se arquea, acortar el rango de extensión de las piernas."],
    "tags": ["core", "control_motor", "salud_lumbar", "postura"]
  },
  {
    "id": "bird-dog",
    "nombre": "Bird dog",
    "nombres_alternativos": ["Pájaro-perro", "Cuadrupedia cruzada"],
    "familia": "core",
    "patron_movimiento": "anti_rotacion",
    "zona": "core",
    "musculos_principales": ["erectores_espinales", "gluteo_mayor"],
    "musculos_secundarios": ["deltoides_anterior", "transverso_abdominal"],
    "descripcion": "Ejercicio en cuatro puntos de apoyo extendiendo un brazo y la pierna contralateral para entrenar la estabilidad de la columna y cadena posterior.",
    "ejecucion_pasos": [
      "Colócate en cuadrupedia con manos debajo de hombros y rodillas bajo caderas.",
      "Mantén la columna neutra y el abdomen activo.",
      "Extiende el brazo derecho hacia adelante y la pierna izquierda recta hacia atrás hasta alinearlos con el tronco.",
      "Aguanta un segundo arriba sin rotar la pelvis.",
      "Regresa al suelo y alterna con el otro lado."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["dead-bug"],
    "precauciones": ["No arquear la zona lumbar ni girar la pelvis."],
    "tags": ["salud_lumbar", "core", "gluteos", "estabilidad"]
  },
  {
    "id": "press-pallof",
    "nombre": "Press Pallof en polea o banda",
    "nombres_alternativos": ["Pallof press"],
    "familia": "core",
    "patron_movimiento": "anti_rotacion",
    "zona": "core",
    "musculos_principales": ["oblicuo_externo", "oblicuo_interno", "transverso_abdominal"],
    "musculos_secundarios": ["recto_abdominal", "deltoides_anterior", "gluteo_medio"],
    "descripcion": "Ejercicio de anti-rotación donde se extiende los brazos al frente resistiendo la fuerza lateral que ejerce una polea o banda elástica.",
    "ejecucion_pasos": [
      "Párate de lado a una torre de polea o anclaje de banda elástica a la altura del pecho.",
      "Sujeta el asa con ambas manos contra el centro del pecho.",
      "Pies al ancho de hombros con rodillas semiflexionadas y postura atlética firme.",
      "Extiende los brazos rectos hacia adelante resistiendo la torsión del cable.",
      "Aguanta 2 segundos con los brazos extendidos y regresa despacio al pecho."
    ],
    "equipamiento": ["polea", "banda_elastica"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["plancha-lateral"],
    "precauciones": ["No permitir que los hombros o caderas roten hacia la polea."],
    "tags": ["anti_rotacion", "core", "polea", "funcional", "rendimiento"]
  },
  {
    "id": "giros-rusos",
    "nombre": "Giros rusos con peso",
    "nombres_alternativos": ["Russian twists"],
    "familia": "core",
    "patron_movimiento": "rotacion",
    "zona": "core",
    "musculos_principales": ["oblicuo_externo", "oblicuo_interno"],
    "musculos_secundarios": ["recto_abdominal", "iliopsoas"],
    "descripcion": "Rotación de tronco sentado con el torso inclinado hacia atrás y pies elevados o apoyados, sosteniendo un disco o mancuerna.",
    "ejecucion_pasos": [
      "Siéntate con las rodillas dobladas y reclina el torso a 45 grados manteniendo la espalda recta.",
      "Sostén una mancuerna o disco frente al pecho.",
      "Gira el torso llevando el peso hacia un lado cerca de la cadera.",
      "Rota de manera fluida hacia el lado contrario sintiendo los oblicuos."
    ],
    "equipamiento": ["disco", "mancuernas", "peso_corporal", "esterilla"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-pallof"],
    "precauciones": ["Rotar desde el torso y caja torácica, no solo moviendo los brazos."],
    "tags": ["core", "oblicuos", "rotacion", "disco"]
  },
  {
    "id": "cargada-de-potencia",
    "nombre": "Cargada de potencia con barra",
    "nombres_alternativos": ["Power clean", "Cargada olímpica"],
    "familia": "potencia",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "isquiotibiales", "trapecio"],
    "musculos_secundarios": ["cuadriceps", "deltoides_lateral", "erectores_espinales", "gemelos"],
    "descripcion": "Levantamiento explosivo donde se acelera una barra desde el suelo recibiéndola sobre los hombros en posición de sentadilla parcial.",
    "ejecucion_pasos": [
      "Inicia en postura de peso muerto con la espalda rígida y brazos rectos.",
      "Inicia el tirón despegando la barra con las piernas.",
      "Al pasar las rodillas, realiza una triple extensión violenta de tobillos, rodillas y caderas con encogimiento de trapecios.",
      "Métete debajo de la barra rotando los codos rápidamente hacia adelante.",
      "Recibe la barra sobre los deltoides anteriores flexionando ligeramente las rodillas para amortiguar.",
      "Ponte de pie con control antes de descender la barra."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["dos-tiempos-clean-and-jerk", "arrancada-snatch", "kettlebell-swing"],
    "precauciones": ["Requiere instrucción técnica calificada para evitar golpes en clavículas y muñecas."],
    "tags": ["olimpico", "potencia", "barra", "fuerza_explosiva", "atletismo"]
  },
  {
    "id": "dos-tiempos-clean-and-jerk",
    "nombre": "Dos tiempos olímpico",
    "nombres_alternativos": ["Clean and jerk"],
    "familia": "potencia",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "cuadriceps", "deltoides_anterior"],
    "musculos_secundarios": ["isquiotibiales", "trapecio", "triceps_braquial", "core"],
    "descripcion": "Levantamiento clásico olímpico compuesto por una cargada al pecho seguida de un envión sobre la cabeza en tijera o flexión.",
    "ejecucion_pasos": [
      "Realiza una cargada completa llevando la barra desde el suelo a los hombros.",
      "Estabiliza la posición erguido con codos altos.",
      "Efectúa un dip de rodillas corto y salta abriendo los pies en tijera (jerk).",
      "Bloquea los brazos extendidos firmemente con la barra sobre la cabeza.",
      "Junta los pies manteniendo el peso arriba antes de bajar la barra a la plataforma."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["cargada-de-potencia", "arrancada-snatch", "push-press"],
    "precauciones": ["Movimiento altamente técnico que exige gran movilidad de muñecas, hombros y tobillos."],
    "tags": ["olimpico", "potencia", "halterofilia", "fuerza"]
  },
  {
    "id": "arrancada-snatch",
    "nombre": "Arrancada olímpica con barra",
    "nombres_alternativos": ["Snatch", "Arrancada"],
    "familia": "potencia",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["gluteo_mayor", "isquiotibiales", "trapecio"],
    "musculos_secundarios": ["deltoides_anterior", "cuadriceps", "erectores_espinales"],
    "descripcion": "El levantamiento más rápido y dinámico del atletismo de fuerza, elevando la barra desde el suelo hasta encima de la cabeza en un solo movimiento continuo.",
    "ejecucion_pasos": [
      "Toma la barra con agarre muy amplio.",
      "Acelera la barra desde el suelo en triple extensión explosiva.",
      "Desciende de inmediato a una sentadilla profunda debajo de la barra.",
      "Recibe y bloquea la barra con brazos extendidos sobre la cabeza.",
      "Ponte de pie con la barra estabilizada."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["cargada-de-potencia", "dos-tiempos-clean-and-jerk"],
    "precauciones": ["Demanda máxima movilidad articular de hombros y caderas."],
    "tags": ["olimpico", "halterofilia", "potencia", "avanzado"]
  },
  {
    "id": "salto-al-cajon",
    "nombre": "Salto al cajón pliométrico",
    "nombres_alternativos": ["Box jump", "Salto sobre cajón"],
    "familia": "salto",
    "patron_movimiento": "potencia",
    "zona": "inferior",
    "musculos_principales": ["cuadriceps", "gluteo_mayor"],
    "musculos_secundarios": ["gemelos", "isquiotibiales"],
    "descripcion": "Salto vertical explosivo con despegue bipodal aterrizando suavemente sobre una caja o plataforma elevada.",
    "ejecucion_pasos": [
      "Párate frente a un cajón estable a medio paso de distancia.",
      "Flexiona brazos, caderas y rodillas preparándote para el impulso.",
      "Salta de manera explosiva balanceando los brazos hacia arriba.",
      "Aterriza suavemente con ambos pies en el centro del cajón en media sentadilla.",
      "Extiende caderas y baja dando un paso hacia atrás (evitar saltar hacia atrás)."
    ],
    "equipamiento": ["cajon"],
    "tipo": "potencia",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["sentadilla-aerea"],
    "precauciones": ["Priorizar la amortiguación silenciosa del aterrizaje; no utilizar cajones excesivamente altos que comprometan la técnica."],
    "tags": ["pliometria", "potencia", "salto", "cajon", "atletismo"]
  },
  {
    "id": "lanzamiento-balon-al-suelo",
    "nombre": "Lanzamiento de balón medicinal al suelo",
    "nombres_alternativos": ["Medicine ball slam", "Slam ball"],
    "familia": "potencia",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["dorsal_ancho", "recto_abdominal"],
    "musculos_secundarios": ["deltoides_anterior", "gluteo_mayor", "triceps_braquial"],
    "descripcion": "Lanzamiento potente de un balón medicinal sin rebote contra el piso desde una extensión completa sobre la cabeza.",
    "ejecucion_pasos": [
      "De pie con los pies al ancho de hombros sujetando el balón medicinal con ambas manos.",
      "Eleva el balón sobre la cabeza extendiendo caderas y tobillos.",
      "Lanza el balón contra el suelo con máxima fuerza flexionando el tronco y las rodillas.",
      "Recógelo tras el impacto y repite con cadencia alta."
    ],
    "equipamiento": ["balon_medicinal"],
    "tipo": "potencia",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["kettlebell-swing"],
    "precauciones": ["Usar balones específicos sin rebote (slam balls) para evitar impactos en el rostro."],
    "tags": ["acondicionamiento", "potencia", "core", "balon_medicinal"]
  },
  {
    "id": "paseo-del-granjero",
    "nombre": "Paseo del granjero",
    "nombres_alternativos": ["Farmer's walk", "Caminata del granjero"],
    "familia": "transporte",
    "patron_movimiento": "locomocion",
    "zona": "cuerpo_completo",
    "musculos_principales": ["trapecio", "antebrazos"],
    "musculos_secundarios": ["recto_abdominal", "oblicuo_externo", "gluteo_medio", "cuadriceps"],
    "descripcion": "Transporte de cargas pesadas caminando erguido con una mancuerna, pesa rusa o barra en cada mano.",
    "ejecucion_pasos": [
      "Levanta dos mancuernas o barras pesadas desde el suelo con técnica de peso muerto.",
      "Párate completamente erguido con hombros atrás, pecho alto y mirada al frente.",
      "Camina en pasos cortos, rápidos y controlados manteniendo el torso inmóvil.",
      "Deposita las cargas con cuidado flexionando las caderas al terminar la distancia."
    ],
    "equipamiento": ["mancuernas", "kettlebell", "discos"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["empuje-de-trineo"],
    "precauciones": ["No encorvarse hacia adelante ni balancear el cuerpo lateralmente."],
    "tags": ["agarre", "fuerza_funcional", "trapecio", "transporte", "core"]
  },
  {
    "id": "empuje-de-trineo",
    "nombre": "Empuje de trineo con carga",
    "nombres_alternativos": ["Sled push", "Prowler push"],
    "familia": "transporte",
    "patron_movimiento": "locomocion",
    "zona": "cuerpo_completo",
    "musculos_principales": ["cuadriceps", "gluteo_mayor", "gemelos"],
    "musculos_secundarios": ["deltoides_anterior", "recto_abdominal", "triceps_braquial"],
    "descripcion": "Empuje hacia adelante de un trineo cargado con discos sobre césped artificial o pista, generando alta demanda metabólica sin impacto excéntrico.",
    "ejecucion_pasos": [
      "Sujeta los postes verticales del trineo con brazos estirados o flexionados.",
      "Inclina el cuerpo en un ángulo de 45 grados formando una línea recta tobillo-cadera-hombro.",
      "Empuja el suelo con pasos potentes llevando las rodillas hacia adelante.",
      "Mantén un empuje rítmico y constante durante la distancia prescrita."
    ],
    "equipamiento": ["trineo", "discos"],
    "tipo": "acondicionamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["paseo-del-granjero"],
    "precauciones": ["Mantener la columna neutra sin redondear la zona lumbar."],
    "tags": ["acondicionamiento", "potencia", "piernas", "cardiovascular", "trineo"]
  },
  {
    "id": "burpees",
    "nombre": "Burpees clásicos",
    "nombres_alternativos": ["Burpee con flexión", "Salto militar"],
    "familia": "carrera",
    "patron_movimiento": "locomocion_cardiovascular",
    "zona": "cuerpo_completo",
    "musculos_principales": ["pectoral_mayor", "cuadriceps"],
    "musculos_secundarios": ["deltoides_anterior", "triceps_braquial", "gluteo_mayor", "gemelos"],
    "descripcion": "Ejercicio cardiovascular integral combinando sentadilla, apoyo de manos, flexión al suelo, recogida de piernas y salto vertical.",
    "ejecucion_pasos": [
      "Comienza de pie con pies al ancho de hombros.",
      "Flexiona rodillas y apoya las manos en el suelo frente a los pies.",
      "Lanza los pies hacia atrás de un salto cayendo en posición de flexión.",
      "Baja el pecho hasta tocar el suelo.",
      "Empuja el suelo, salta con los pies de vuelta hacia las manos y elévate en un salto vertical con palmada sobre la cabeza."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "cardiovascular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["mountain-climbers", "saltos-en-tijera"],
    "precauciones": ["Amortiguar el salto aterrizando con suavidad en metatarsos."],
    "tags": ["cardiovascular", "hiit", "acondicionamiento", "peso_corporal"]
  },
  {
    "id": "mountain-climbers",
    "nombre": "Escaladores",
    "nombres_alternativos": ["Mountain climbers", "Escalada horizontal"],
    "familia": "core",
    "patron_movimiento": "flexion_de_cadera",
    "zona": "cardiovascular",
    "musculos_principales": ["recto_abdominal", "iliopsoas"],
    "musculos_secundarios": ["deltoides_anterior", "cuadriceps", "gemelos"],
    "descripcion": "Desde posición de plancha alta, se llevan alternadamente las rodillas al pecho en un ritmo rápido y continuo.",
    "ejecucion_pasos": [
      "Adopta la posición de flexión con brazos rectos y cuerpo alineado.",
      "Lleva una rodilla hacia el pecho sin apoyar el pie en el suelo.",
      "Regresa la pierna a la vez que adelantas la otra en un movimiento fluido y dinámico.",
      "Mantén las caderas bajas sin rebotar en exceso."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "cardiovascular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["burpees", "plancha-abdominal-frontal"],
    "precauciones": ["No elevar los glúteos en forma de carpa; mantener la línea de plancha."],
    "tags": ["cardiovascular", "core", "hiit", "peso_corporal"]
  },
  {
    "id": "levantamiento-turco",
    "nombre": "Levantamiento turco con kettlebell",
    "nombres_alternativos": ["Turkish get-up", "TGU"],
    "familia": "movilidad",
    "patron_movimiento": "locomocion",
    "zona": "cuerpo_completo",
    "musculos_principales": ["deltoides_anterior", "recto_abdominal", "gluteo_mayor"],
    "musculos_secundarios": ["manguito_rotador", "triceps_braquial", "oblicuo_externo"],
    "descripcion": "Secuencia fluida de movimientos para levantarse desde el suelo hasta quedar de pie sosteniendo una pesa fija sobre la cabeza en todo momento.",
    "ejecucion_pasos": [
      "Acuéstate boca arriba sosteniendo la kettlebell verticalmente con un brazo extendido.",
      "Flexiona la rodilla del mismo lado y gira sobre el codo contrario para incorporarte.",
      "Pasa a la palma de la mano y eleva la cadera en puente.",
      "Pasa la pierna libre por debajo hasta arrodillarte.",
      "Ponte completamente de pie sin desviar la mirada de la pesa.",
      "Invierte exactamente cada paso para volver a acostarte en el suelo."
    ],
    "equipamiento": ["kettlebell", "mancuernas", "esterilla"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": true,
    "variantes": ["kettlebell-swing"],
    "precauciones": ["Mantener la vista fija en la pesa en todo momento para asegurar el bloqueo del hombro."],
    "tags": ["movilidad", "estabilidad", "kettlebell", "funcional", "hombros"]
  },
  {
    "id": "saltos-con-cuerda",
    "nombre": "Saltos a la comba",
    "nombres_alternativos": ["Jump rope", "Salto a la cuerda"],
    "familia": "carrera",
    "patron_movimiento": "locomocion_cardiovascular",
    "zona": "cardiovascular",
    "musculos_principales": ["gemelos", "soleo"],
    "musculos_secundarios": ["cuadriceps", "deltoides_lateral", "antebrazos"],
    "descripcion": "Salto continuo sobre una cuerda giratoria impulsada por las muñecas, excelente para coordinación, acondicionamiento y reactividad de tobillos.",
    "ejecucion_pasos": [
      "Sostén los mangos a la altura de las caderas con los codos pegados.",
      "Haz girar la cuerda mediante movimientos circulares de las muñecas.",
      "Salta de forma elástica sobre la punta de los pies apenas lo suficiente para que pase la cuerda.",
      "Mantén las rodillas ligeramente desbloqueadas para amortiguar el impacto."
    ],
    "equipamiento": ["cuerda"],
    "tipo": "cardiovascular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["saltos-en-tijera"],
    "precauciones": ["Aterrizar siempre sobre los metatarsos, nunca sobre los talones."],
    "tags": ["cardio", "coordinacion", "gemelos", "cuerda"]
  },
  {
    "id": "saltos-en-tijera",
    "nombre": "Saltos en tijera",
    "nombres_alternativos": ["Jumping jacks", "Tijeras de salto"],
    "familia": "carrera",
    "patron_movimiento": "locomocion_cardiovascular",
    "zona": "cardiovascular",
    "musculos_principales": ["gemelos", "deltoides_lateral"],
    "musculos_secundarios": ["cuadriceps", "gluteo_medio"],
    "descripcion": "Salto rítmico abriendo simultáneamente piernas y brazos por encima de la cabeza y volviendo a la posición cerrada.",
    "ejecucion_pasos": [
      "Inicia de pie con los brazos a los lados y pies juntos.",
      "Salta abriendo los pies más allá del ancho de hombros y llevando las manos sobre la cabeza.",
      "Vuelve a saltar cerrando piernas y brazos de forma continua y coordinada."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "cardiovascular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["saltos-con-cuerda", "burpees"],
    "precauciones": ["Aterrizar suavemente con rodillas ligeramente flexionadas."],
    "tags": ["calentamiento", "cardiovascular", "principiante", "peso_corporal"]
  },
  {
    "id": "remoergometro",
    "nombre": "Remo en máquina de remo",
    "nombres_alternativos": ["Indoor rowing", "Remoergómetro"],
    "familia": "carrera",
    "patron_movimiento": "locomocion_cardiovascular",
    "zona": "cardiovascular",
    "musculos_principales": ["cuadriceps", "gluteo_mayor", "dorsal_ancho"],
    "musculos_secundarios": ["biceps_braquial", "isquiotibiales", "erectores_espinales", "deltoides_posterior"],
    "descripcion": "Acondicionamiento cardiovascular integral sentado que reproduce la mecánica del remo en agua integrando empuje de piernas y tracción de brazos.",
    "ejecucion_pasos": [
      "Ajusta los pies en las plataformas y toma la empuñadura con brazos rectos.",
      "Inicia el impulso empujando con fuerza las piernas.",
      "Al extender las piernas, inclina el torso ligeramente hacia atrás.",
      "Completa tirando de la empuñadura hacia las costillas inferiores.",
      "Recupera extendiendo brazos, luego flexionando caderas y finalmente doblando las rodillas."
    ],
    "equipamiento": ["maquina"],
    "tipo": "cardiovascular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["carrera-en-cinta"],
    "precauciones": ["Secuencia correcta: piernas, cadera, brazos en el tirón; brazos, cadera, piernas en el retorno."],
    "tags": ["cardio", "espalda", "piernas", "maquina", "resistencia"]
  },
  {
    "id": "carrera-en-cinta",
    "nombre": "Carrera en cinta estática",
    "nombres_alternativos": ["Treadmill running", "Trote en cinta"],
    "familia": "carrera",
    "patron_movimiento": "locomocion_cardiovascular",
    "zona": "cardiovascular",
    "musculos_principales": ["cuadriceps", "gemelos", "gluteo_mayor"],
    "musculos_secundarios": ["isquiotibiales", "soleo", "recto_abdominal"],
    "descripcion": "Locomoción cardiovascular continua corriendo sobre una cinta rodante motorizada con velocidad e inclinación regulable.",
    "ejecucion_pasos": [
      "Colócate sobre la cinta e inicia a paso suave aumentando la velocidad gradualmente.",
      "Mantén la mirada al frente y el tronco erguido.",
      "Bracea naturalmente en coordinación con las zancadas.",
      "Aterriza con el mediopié debajo del centro de gravedad."
    ],
    "equipamiento": ["maquina"],
    "tipo": "cardiovascular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["remoergometro"],
    "precauciones": ["Usar calzado adecuado y fijar la pinza de seguridad de la cinta."],
    "tags": ["cardio", "resistencia", "carrera", "maquina"]
  },
  {
    "id": "gato-camello",
    "nombre": "Gato-camello en cuadrupedia",
    "nombres_alternativos": ["Cat-cow", "Gato vaca"],
    "familia": "movilidad",
    "patron_movimiento": "movilidad",
    "zona": "movilidad",
    "musculos_principales": ["erectores_espinales", "recto_abdominal"],
    "musculos_secundarios": ["trapecio"],
    "descripcion": "Ejercicio suave de movilidad de columna alternando flexión y extensión vertebral en posición de cuatro apoyos.",
    "ejecucion_pasos": [
      "Colócate en cuatro apoyos con manos bajo hombros y rodillas bajo caderas.",
      "Inhala mientras dejas caer el abdomen y miras suavemente hacia el techo (vaca/camello).",
      "Exhala mientras redondeas la columna empujando el suelo y mirando hacia el ombligo (gato).",
      "Muévete con suavidad coordinando respiración y movimiento."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "movilidad",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["rotacion-de-cadera-90-90", "perro-boca-abajo"],
    "precauciones": ["No forzar rangos dolorosos; el movimiento debe ser suave y fluido."],
    "tags": ["movilidad", "columna", "salud_lumbar", "calentamiento"]
  },
  {
    "id": "rotacion-de-cadera-90-90",
    "nombre": "Movilidad de cadera 90/90",
    "nombres_alternativos": ["90/90 hip mobility", "Rotación de cadera 90-90"],
    "familia": "movilidad",
    "patron_movimiento": "movilidad",
    "zona": "movilidad",
    "musculos_principales": ["gluteo_medio", "aductor_mayor"],
    "musculos_secundarios": ["gluteo_mayor", "iliopsoas"],
    "descripcion": "Ejercicio sentado para mejorar simultáneamente la rotación interna y externa de la cadera.",
    "ejecucion_pasos": [
      "Siéntate en el suelo con una pierna doblada al frente a 90 grados y la otra al lado también a 90 grados.",
      "Mantén el torso erguido apoyando suavemente las manos en el suelo si es necesario.",
      "Inclina el torso sobre la pierna delantera para sentir el estiramiento en la cadera.",
      "Gira las rodillas hacia el otro lado sin mover los talones de su sitio para alternar."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "movilidad",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["gato-camello"],
    "precauciones": ["No forzar si hay molestias en la parte interna de la rodilla."],
    "tags": ["movilidad", "cadera", "flexibilidad", "prevencion_lesiones"]
  },
  {
    "id": "perro-boca-abajo",
    "nombre": "Perro boca abajo",
    "nombres_alternativos": ["Downward dog", "Adho Mukha Svanasana"],
    "familia": "movilidad",
    "patron_movimiento": "movilidad",
    "zona": "movilidad",
    "musculos_principales": ["isquiotibiales", "gemelos"],
    "musculos_secundarios": ["dorsal_ancho", "deltoides_anterior", "soleo"],
    "descripcion": "Postura clásica de estiramiento y movilidad donde el cuerpo forma una V invertida elongando la cadena posterior y hombros.",
    "ejecucion_pasos": [
      "Desde posición de plancha, empuja con las manos elevando las caderas hacia el techo.",
      "Forma una V invertida manteniendo la espalda recta.",
      "Lleva los talones en dirección al suelo para estirar pantorrillas e isquiotibiales.",
      "Respira profundamente durante 20-30 segundos."
    ],
    "equipamiento": ["peso_corporal", "esterilla"],
    "tipo": "movilidad",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["gato-camello"],
    "precauciones": ["Flexionar ligeramente las rodillas si los isquiotibiales limitan la espalda recta."],
    "tags": ["movilidad", "estiramiento", "cadena_posterior", "yoga"]
  },
  {
    "id": "dislocaciones-de-hombro-con-banda",
    "nombre": "Dislocaciones de hombro con banda",
    "nombres_alternativos": ["Shoulder pass-throughs", "Movilidad de hombros con pica"],
    "familia": "movilidad",
    "patron_movimiento": "movilidad",
    "zona": "movilidad",
    "musculos_principales": ["pectoral_mayor", "deltoides_anterior"],
    "musculos_secundarios": ["manguito_rotador", "trapecio"],
    "descripcion": "Rotación completa de hombros pasando una banda elástica o pica desde delante de las caderas hasta detrás de la espalda con brazos extendidos.",
    "ejecucion_pasos": [
      "Sujeta una banda elástica con un agarre amplio frente a tus muslos.",
      "Con los brazos rectos, elévalos por encima de la cabeza.",
      "Continúa el movimiento hacia atrás hasta tocar la zona lumbar.",
      "Regresa suavemente hacia el frente por el mismo trayecto."
    ],
    "equipamiento": ["banda_elastica"],
    "tipo": "movilidad",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["gato-camello"],
    "precauciones": ["Usar un agarre lo suficientemente amplio para que los codos no se doblen ni duela el hombro."],
    "tags": ["movilidad", "hombros", "banda_elastica", "calentamiento"]
  }
];
