export const upperPushExercises = [
  {
    "id": "press-banca-plano-barra",
    "nombre": "Press de banca plano con barra",
    "nombres_alternativos": ["Bench press", "Press de pecho con barra", "Press plano"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior", "triceps_braquial"],
    "descripcion": "Ejercicio fundamental de empuje horizontal acostado en banco donde se baja una barra al pecho y se empuja hacia arriba hasta extender los brazos.",
    "ejecucion_pasos": [
      "Acuéstate sobre el banco plano con los ojos directamente debajo de la barra.",
      "Apoya los pies firmes en el suelo y retrae las escápulas creando un arco lumbar natural.",
      "Sujeta la barra con un agarre ligeramente superior al ancho de hombros.",
      "Saca la barra del soporte y estabilízala sobre el pecho con los codos bloqueados.",
      "Inhala y baja la barra de forma controlada hasta rozar la parte media del esternón.",
      "Empuja la barra en una trayectoria ligeramente diagonal hacia atrás hasta la extensión de codos."
    ],
    "equipamiento": ["barra", "banco", "soporte_o_rack", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-banca-inclinado-barra", "press-banca-declinado-barra", "press-banca-plano-mancuernas", "flexiones-de-brazos"],
    "precauciones": ["Mantener las escápulas retraídas durante todo el levantamiento.", "Evitar rebotar la barra en el pecho.", "No abrir los codos a 90 grados para proteger los hombros."],
    "tags": ["pecho", "pectoral", "triceps", "fuerza", "barra", "powerlifting"]
  },
  {
    "id": "press-banca-inclinado-barra",
    "nombre": "Press de banca inclinado con barra",
    "nombres_alternativos": ["Incline bench press"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "deltoides_anterior"],
    "musculos_secundarios": ["triceps_braquial"],
    "descripcion": "Press de banca en banco inclinado a 30-45 grados que pone mayor énfasis en el haz clavicular (pecho superior) y deltoides anterior.",
    "ejecucion_pasos": [
      "Ajusta el banco a unos 30 a 45 grados de inclinación.",
      "Acuéstate con los pies firmes y las escápulas retraídas.",
      "Sujeta la barra a la anchura de hombros o ligeramente más amplio.",
      "Desciende la barra de forma controlada hacia la parte alta del pecho.",
      "Empuja con fuerza hasta extender los brazos sin perder la retracción escapular."
    ],
    "equipamiento": ["barra", "banco", "soporte_o_rack", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-banca-plano-barra", "press-banca-inclinado-mancuernas"],
    "precauciones": ["Una inclinación superior a 45 grados traslada casi todo el esfuerzo a los deltoides."],
    "tags": ["pecho_superior", "pectoral", "barra", "hipertrofia"]
  },
  {
    "id": "press-banca-declinado-barra",
    "nombre": "Press de banca declinado con barra",
    "nombres_alternativos": ["Decline bench press"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["triceps_braquial", "deltoides_anterior"],
    "descripcion": "Press en banco con inclinación negativa que enfatiza las fibras inferiores del pectoral mayor reduciendo el estrés en el hombro anterior.",
    "ejecucion_pasos": [
      "Asegura las piernas en los rodillos del banco declinado y acuéstate.",
      "Sujeta la barra con agarre medio y retírala del soporte.",
      "Baja la barra de forma controlada hacia la parte baja del pectoral.",
      "Empuja la barra verticalmente hasta bloquear los codos."
    ],
    "equipamiento": ["barra", "banco", "soporte_o_rack", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-banca-plano-barra", "fondos-en-paralelas"],
    "precauciones": ["Contar siempre con soporte seguro o compañero dado el ángulo de salida."],
    "tags": ["pecho_inferior", "pectoral", "barra"]
  },
  {
    "id": "press-banca-plano-mancuernas",
    "nombre": "Press de banca plano con mancuernas",
    "nombres_alternativos": ["Dumbbell bench press", "Press con mancuernas plano"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior", "triceps_braquial"],
    "descripcion": "Empuje horizontal con mancuernas que permite mayor rango de movimiento, convergencia de brazos y trabajo equilibrado bilateral.",
    "ejecucion_pasos": [
      "Siéntate en el banco con las mancuernas apoyadas en los muslos.",
      "Túmbate hacia atrás ayudándote de las rodillas para colocar las pesas a los lados del pecho.",
      "Mantén los pies apoyados, escápulas retraídas y codos a unos 45-60 grados respecto al torso.",
      "Empuja las mancuernas hacia arriba en arco suave hasta que casi se toquen sobre el pecho.",
      "Baja controladamente sintiendo el estiramiento pectoral."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-banca-plano-barra", "press-banca-inclinado-mancuernas"],
    "precauciones": ["No dejar caer las mancuernas bruscamente al terminar; llevarlas de vuelta a los muslos incorporándote."],
    "tags": ["pecho", "mancuernas", "hipertrofia", "equilibrio"]
  },
  {
    "id": "press-banca-inclinado-mancuernas",
    "nombre": "Press inclinado con mancuernas",
    "nombres_alternativos": ["Incline dumbbell press"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "deltoides_anterior"],
    "musculos_secundarios": ["triceps_braquial"],
    "descripcion": "Empuje en banco inclinado con mancuernas para estimular el haz clavicular con libertad articular para muñecas y hombros.",
    "ejecucion_pasos": [
      "Ajusta el banco a 30-45 grados y túmbate con las mancuernas junto al pecho.",
      "Empuja las mancuernas hacia arriba convergiendo levemente en la parte alta.",
      "Desciende controlando el peso hasta sentir un buen estiramiento en la porción superior del pecho.",
      "Repite manteniendo la espalda alta bien apoyada."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-banca-inclinado-barra", "press-banca-plano-mancuernas"],
    "precauciones": ["Controlar la apertura de codos para evitar molestias en el manguito rotador."],
    "tags": ["pecho_superior", "mancuernas", "hombros", "hipertrofia"]
  },
  {
    "id": "press-pecho-maquina",
    "nombre": "Press de pecho en máquina",
    "nombres_alternativos": ["Chest press machine", "Prensa de pecho"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior", "triceps_braquial"],
    "descripcion": "Empuje horizontal guiado en máquina que estabiliza el recorrido facilitando llegar a la fatiga muscular de forma segura.",
    "ejecucion_pasos": [
      "Ajusta la altura del asiento para que los agarres queden a la altura de la parte media del pecho.",
      "Apoya la espalda firmemente contra el respaldo.",
      "Empuja los agarres hacia adelante extendiendo los brazos sin hiperextender los codos.",
      "Regresa controlando el peso hasta que los codos queden a la altura del torso."
    ],
    "equipamiento": ["maquina"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-banca-plano-barra", "press-banca-plano-mancuernas"],
    "precauciones": ["No despegar la espalda del respaldo al empujar."],
    "tags": ["maquina", "pecho", "principiante", "hipertrofia"]
  },
  {
    "id": "flexiones-de-brazos",
    "nombre": "Flexiones de brazos",
    "nombres_alternativos": ["Push-ups", "Lagartijas", "Fondos en el suelo"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "triceps_braquial"],
    "musculos_secundarios": ["deltoides_anterior", "recto_abdominal", "serrato_anterior"],
    "descripcion": "Clásico ejercicio de calistenia donde se eleva el peso corporal desde el suelo mediante empuje de brazos manteniendo el cuerpo en línea recta.",
    "ejecucion_pasos": [
      "Apoya las manos en el suelo ligeramente más separadas que el ancho de hombros.",
      "Extiende las piernas hacia atrás apoyándote en las puntas de los pies.",
      "Forma una línea recta sólida desde la cabeza hasta los talones activando glúteos y abdomen.",
      "Flexiona los codos descendiendo el pecho hasta casi rozar el suelo.",
      "Los codos deben formar un ángulo de unos 45 grados con el cuerpo en forma de flecha.",
      "Empuja el suelo con fuerza hasta extender los brazos completamente."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["flexiones-diamante", "flexiones-declinadas", "flexiones-arqueras", "press-banca-plano-barra"],
    "precauciones": ["No dejar caer la cadera ni arquear la zona lumbar.", "Evitar abrir los codos a 90 grados respecto al torso."],
    "tags": ["calistenia", "peso_corporal", "pecho", "triceps", "basico"]
  },
  {
    "id": "flexiones-diamante",
    "nombre": "Flexiones diamante",
    "nombres_alternativos": ["Diamond push-ups", "Flexiones en triángulo"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial", "pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior", "recto_abdominal"],
    "descripcion": "Variante de flexiones con las manos juntas formando un rombo o diamante con los dedos, aumentando significativamente la demanda sobre los tríceps.",
    "ejecucion_pasos": [
      "Coloca las manos en el suelo bajo el centro del pecho uniendo pulgares e índices en forma de diamante.",
      "Cuerpo en plancha firme con abdomen contraído.",
      "Baja el pecho hacia las manos manteniendo los codos pegados a los costados.",
      "Empuja fuerte con las palmas para extender los codos."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["flexiones-de-brazos", "fondos-en-paralelas"],
    "precauciones": ["Si genera molestia en las muñecas, separar ligeramente las manos manteniendo un agarre cerrado."],
    "tags": ["triceps", "calistenia", "peso_corporal", "empuje"]
  },
  {
    "id": "flexiones-declinadas",
    "nombre": "Flexiones declinadas",
    "nombres_alternativos": ["Decline push-ups", "Flexiones con pies elevados"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "deltoides_anterior"],
    "musculos_secundarios": ["triceps_braquial", "recto_abdominal"],
    "descripcion": "Flexiones con los pies elevados sobre un banco o soporte, aumentando la carga corporal y el estímulo en el pectoral superior y deltoides.",
    "ejecucion_pasos": [
      "Coloca las puntas de los pies sobre un banco o escalón y las manos en el suelo.",
      "Alinea el cuerpo en posición de plancha rígida.",
      "Desciende el pecho hacia el suelo doblando los codos.",
      "Empuja hacia arriba con control hasta bloquear brazos."
    ],
    "equipamiento": ["peso_corporal", "banco"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["flexiones-de-brazos", "pike-push-ups"],
    "precauciones": ["Evitar hiperextender el cuello; mantener la mirada en el suelo."],
    "tags": ["calistenia", "pecho_superior", "hombros", "peso_corporal"]
  },
  {
    "id": "flexiones-arqueras",
    "nombre": "Flexiones arqueras",
    "nombres_alternativos": ["Archer push-ups"],
    "familia": "press",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "triceps_braquial"],
    "musculos_secundarios": ["deltoides_anterior", "recto_abdominal"],
    "descripcion": "Ejercicio avanzado de calistenia donde se desciende hacia un lado mientras el brazo opuesto se extiende completamente como un arquero.",
    "ejecucion_pasos": [
      "Coloca las manos en el suelo con una apertura muy ancha.",
      "Desplaza el peso y desciende hacia un lado flexionando ese brazo mientras el otro se mantiene estirado.",
      "Empuja para volver al centro y repite hacia el lado opuesto."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": true,
    "variantes": ["flexiones-de-brazos"],
    "precauciones": ["Requiere gran fuerza previa en flexiones tradicionales."],
    "tags": ["calistenia", "avanzado", "unilateral", "pecho"]
  },
  {
    "id": "fondos-en-paralelas",
    "nombre": "Fondos en paralelas",
    "nombres_alternativos": ["Dips en paralelas", "Fondos de pecho y tríceps"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial", "pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior"],
    "descripcion": "Ejercicio de suspensión entre barras paralelas donde se flexiona y extiende los brazos levantando el propio peso corporal.",
    "ejecucion_pasos": [
      "Súbete a las barras paralelas sujetando los agarres con brazos estirados.",
      "Inclina el torso ligeramente hacia adelante si deseas enfocar más el pecho, o más vertical para tríceps.",
      "Flexiona los codos bajando el cuerpo de manera controlada hasta un ángulo aproximado de 90 grados.",
      "Empuja firmemente hacia abajo extendiendo los codos hasta la posición inicial."
    ],
    "equipamiento": ["paralelas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["fondos-en-banco", "fondos-en-anillas", "flexiones-diamante"],
    "precauciones": ["No descender en exceso si no se cuenta con suficiente movilidad escapulohumeral.", "Mantener los hombros alejados de las orejas sin encogerlos."],
    "tags": ["calistenia", "triceps", "pecho", "fuerza", "peso_corporal"]
  },
  {
    "id": "fondos-en-banco",
    "nombre": "Fondos en banco",
    "nombres_alternativos": ["Bench dips"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial"],
    "musculos_secundarios": ["deltoides_anterior", "pectoral_mayor"],
    "descripcion": "Fondos apoyando las manos en el borde de un banco y los pies en el suelo, excelente alternativa accesible para tríceps.",
    "ejecucion_pasos": [
      "Siéntate en el borde de un banco y apoya las palmas junto a las caderas con los dedos hacia adelante.",
      "Adelanta los pies y saca los glúteos del banco con brazos extendidos.",
      "Flexiona los codos hacia atrás descendiendo hasta los 90 grados.",
      "Presiona con las palmas y extiende los codos para subir."
    ],
    "equipamiento": ["banco", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["fondos-en-paralelas", "flexiones-diamante"],
    "precauciones": ["Mantener la espalda cerca del banco para no forzar la rotación interna del hombro."],
    "tags": ["triceps", "principiante", "banco", "peso_corporal"]
  },
  {
    "id": "fondos-en-anillas",
    "nombre": "Fondos en anillas",
    "nombres_alternativos": ["Ring dips"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor", "triceps_braquial"],
    "musculos_secundarios": ["deltoides_anterior", "serrato_anterior", "recto_abdominal"],
    "descripcion": "Fondos realizados en anillas de gimnasia, añadiendo una gran demanda de estabilización para pectorales y hombros.",
    "ejecucion_pasos": [
      "Sostente en suspensión sobre las anillas con codos extendidos y anillas pegadas al cuerpo.",
      "Desciende flexionando los codos manteniendo las anillas controladas y estables.",
      "Baja hasta que el bíceps toque la anilla.",
      "Empuja hacia abajo y gira ligeramente las anillas hacia afuera en la parte superior."
    ],
    "equipamiento": ["anillas", "suspension", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["fondos-en-paralelas"],
    "precauciones": ["Requiere sólida base en fondos en paralelas antes de intentar en anillas inestables."],
    "tags": ["anillas", "calistenia", "avanzado", "estabilidad", "fuerza"]
  },
  {
    "id": "press-militar-barra",
    "nombre": "Press militar con barra",
    "nombres_alternativos": ["Overhead press", "Press de hombros de pie", "OHP"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["deltoides_anterior", "deltoides_lateral"],
    "musculos_secundarios": ["triceps_braquial", "trapecio", "recto_abdominal", "gluteo_mayor"],
    "descripcion": "Empuje vertical estricto de pie con barra apoyada sobre las clavículas hasta el bloqueo por encima de la cabeza.",
    "ejecucion_pasos": [
      "Sujeta la barra a la anchura de hombros con los codos apuntando ligeramente hacia adelante.",
      "Párate con pies al ancho de caderas, glúteos y abdomen fuertemente contraídos.",
      "Retrae levemente la cabeza para permitir el paso recto de la barra.",
      "Empuja la barra verticalmente hacia el techo de forma explosiva.",
      "Una vez que la barra pasa la frente, lleva la cabeza suavemente al frente bloqueando los brazos sobre la línea media.",
      "Desciende controladamente de vuelta a las clavículas."
    ],
    "equipamiento": ["barra", "discos", "soporte_o_rack"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-hombros-mancuernas", "push-press", "press-arnold"],
    "precauciones": ["No arquear excesivamente la zona lumbar para empujar el peso.", "Mantener el abdomen y glúteos rígidos."],
    "tags": ["hombros", "deltoides", "fuerza", "barra", "basico"]
  },
  {
    "id": "press-hombros-mancuernas",
    "nombre": "Press de hombros con mancuernas sentado",
    "nombres_alternativos": ["Seated dumbbell shoulder press", "Press militar con mancuernas"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["deltoides_anterior", "deltoides_lateral"],
    "musculos_secundarios": ["triceps_braquial", "trapecio"],
    "descripcion": "Empuje vertical sentado en banco con respaldo casi vertical, aislando el trabajo en hombros y tríceps.",
    "ejecucion_pasos": [
      "Siéntate en un banco con respaldo a 75-80 grados sosteniendo las mancuernas a la altura de las orejas.",
      "Mantén las escápulas apoyadas y los codos en el plano escapular (ligeramente al frente).",
      "Empuja las mancuernas hacia arriba en un arco suave hasta extender los brazos.",
      "Baja controladamente hasta que las pesas queden a la altura del mentón o las orejas."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-militar-barra", "press-arnold"],
    "precauciones": ["No dejar caer los codos excesivamente por debajo de los hombros si hay molestias articulares."],
    "tags": ["hombros", "deltoides", "mancuernas", "hipertrofia"]
  },
  {
    "id": "press-arnold",
    "nombre": "Press Arnold con mancuernas",
    "nombres_alternativos": ["Arnold press"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["deltoides_anterior", "deltoides_lateral"],
    "musculos_secundarios": ["triceps_braquial", "trapecio"],
    "descripcion": "Variante de press con mancuernas que incorpora una rotación de muñecas y hombros durante la subida, estimulando todos los haces del deltoides.",
    "ejecucion_pasos": [
      "Inicia sentado sosteniendo las mancuernas frente a la parte alta del pecho con las palmas mirando hacia ti.",
      "A medida que empujas hacia arriba, rota los brazos hacia afuera abriendo los codos.",
      "Termina en la parte alta con las palmas mirando hacia adelante en extensión completa.",
      "Invierte el movimiento girando de nuevo las palmas hacia ti al descender."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["press-hombros-mancuernas", "press-militar-barra"],
    "precauciones": ["Utilizar cargas más moderadas que en el press convencional por la rotación continua."],
    "tags": ["hombros", "deltoides", "mancuernas", "hipertrofia"]
  },
  {
    "id": "push-press",
    "nombre": "Push press con barra",
    "nombres_alternativos": ["Press con impulso"],
    "familia": "press",
    "patron_movimiento": "potencia",
    "zona": "cuerpo_completo",
    "musculos_principales": ["deltoides_anterior", "cuadriceps"],
    "musculos_secundarios": ["triceps_braquial", "gluteo_mayor", "erectores_espinales"],
    "descripcion": "Empuje vertical dinámico donde se utiliza una ligera flexión y extensión de rodillas (dip and drive) para propulsar la barra por encima de la cabeza.",
    "ejecucion_pasos": [
      "Sostén la barra en posición de rack sobre los hombros.",
      "Realiza un dip corto flexionando rodillas unos 10-15 cm con el torso vertical.",
      "Extiende explosivamente las piernas transfiriendo la fuerza a la barra.",
      "Completa el empuje con los brazos bloqueando la barra firmemente sobre la cabeza.",
      "Baja la barra de regreso a los hombros amortiguando el impacto con las rodillas."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["press-militar-barra"],
    "precauciones": ["Mantener el torso recto en el dip sin inclinarse hacia adelante."],
    "tags": ["potencia", "hombros", "barra", "olimpico", "fuerza"]
  },
  {
    "id": "flexiones-hspu",
    "nombre": "Flexiones de pino",
    "nombres_alternativos": ["Handstand push-ups", "HSPU", "Flexiones en vertical"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["deltoides_anterior", "triceps_braquial"],
    "musculos_secundarios": ["deltoides_lateral", "trapecio", "recto_abdominal"],
    "descripcion": "Avanzado ejercicio de calistenia donde se realiza una flexión vertical en posición invertida apoyado contra la pared o en equilibrio libre.",
    "ejecucion_pasos": [
      "Patea hacia arriba para colocarte en posición de pino contra una pared.",
      "Cuerpo firme con el abdomen apretado y las manos a la anchura de hombros.",
      "Flexiona los codos bajando la cabeza hacia adelante formando un trípode imaginario con las manos.",
      "Empuja el suelo con fuerza hasta volver al bloqueo total de codos."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["pike-push-ups", "press-militar-barra"],
    "precauciones": ["Requiere gran fuerza de hombros y control cervical.", "Colocar colchoneta debajo de la cabeza para seguridad."],
    "tags": ["calistenia", "avanzado", "hombros", "peso_corporal"]
  },
  {
    "id": "pike-push-ups",
    "nombre": "Pike push-ups",
    "nombres_alternativos": ["Flexiones en pica"],
    "familia": "press",
    "patron_movimiento": "empuje_vertical",
    "zona": "superior",
    "musculos_principales": ["deltoides_anterior", "triceps_braquial"],
    "musculos_secundarios": ["trapecio", "serrato_anterior"],
    "descripcion": "Flexión con las caderas elevadas en V invertida, simulando el ángulo de un press de hombros con peso corporal.",
    "ejecucion_pasos": [
      "Comienza en posición de flexión y camina con los pies hacia las manos elevando la cadera.",
      "Forma una V invertida con la espalda recta.",
      "Baja la coronilla hacia el suelo delante de las manos.",
      "Empuja en diagonal hacia atrás para volver a la posición de pica."
    ],
    "equipamiento": ["peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["flexiones-hspu", "flexiones-de-brazos"],
    "precauciones": ["Mantener la cadera alta durante todo el rango."],
    "tags": ["calistenia", "hombros", "triceps", "peso_corporal"]
  },
  {
    "id": "aperturas-mancuernas-plano",
    "nombre": "Aperturas con mancuernas en banco plano",
    "nombres_alternativos": ["Dumbbell flyes", "Aperturas de pecho"],
    "familia": "aperturas",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior"],
    "descripcion": "Aislamiento pectoral abriendo los brazos en arco sobre un banco plano, maximizando el estiramiento muscular.",
    "ejecucion_pasos": [
      "Acuéstate en banco plano con las mancuernas sobre el pecho y codos con leve flexión fija.",
      "Abre los brazos hacia los lados en un movimiento amplio de abrazo.",
      "Baja hasta que los codos queden al nivel del pecho sintiendo el estiramiento.",
      "Cierra los brazos siguiendo el mismo arco contrayendo los pectorales en la cima."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["cruce-de-poleas", "contractora-pec-deck"],
    "precauciones": ["No hiperflexionar ni extender bruscamente los codos durante el trayecto.", "Evitar bajar las mancuernas más allá del confort articular."],
    "tags": ["pecho", "aislamiento", "mancuernas", "hipertrofia"]
  },
  {
    "id": "cruce-de-poleas",
    "nombre": "Cruce de poleas altas",
    "nombres_alternativos": ["Cable crossover", "Cruces en polea"],
    "familia": "aperturas",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior"],
    "descripcion": "Aislamiento en poleas donde se juntan los brazos frente al cuerpo con tensión continua en todo el rango.",
    "ejecucion_pasos": [
      "Coloca las poleas a una altura superior a los hombros y toma un asa en cada mano.",
      "Da un paso adelante con el torso ligeramente inclinado y los codos semiflexionados.",
      "Junta las manos hacia abajo y al centro cruzándolas levemente frente a la cadera.",
      "Aprieta los pectorales y regresa lentamente abriendo los brazos."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["aperturas-mancuernas-plano", "contractora-pec-deck"],
    "precauciones": ["Mantener la ligera flexión de codos fija sin convertirlo en un press."],
    "tags": ["polea", "pecho", "aislamiento", "tension_continua"]
  },
  {
    "id": "contractora-pec-deck",
    "nombre": "Pec deck en máquina",
    "nombres_alternativos": ["Contractora de pecho", "Machine flyes"],
    "familia": "aperturas",
    "patron_movimiento": "empuje_horizontal",
    "zona": "superior",
    "musculos_principales": ["pectoral_mayor"],
    "musculos_secundarios": ["deltoides_anterior"],
    "descripcion": "Apertura guiada en máquina que aísla el pectoral sin requerir balance de pesos libres.",
    "ejecucion_pasos": [
      "Ajusta el asiento para que los agarres o almohadillas queden a la altura del pecho.",
      "Apoya la espalda firme y junta los brazos al frente hasta que se toquen.",
      "Contrae intensamente un segundo en el centro.",
      "Abre lentamente hasta el punto de estiramiento cómodo."
    ],
    "equipamiento": ["maquina"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["cruce-de-poleas", "aperturas-mancuernas-plano"],
    "precauciones": ["No forzar un rango de apertura excesivo que comprometa la cápsula del hombro."],
    "tags": ["maquina", "pecho", "aislamiento", "principiante"]
  },
  {
    "id": "elevaciones-laterales-mancuernas",
    "nombre": "Elevaciones laterales con mancuernas",
    "nombres_alternativos": ["Lateral raises", "Vuelos laterales"],
    "familia": "elevacion",
    "patron_movimiento": "elevacion",
    "zona": "superior",
    "musculos_principales": ["deltoides_lateral"],
    "musculos_secundarios": ["trapecio", "deltoides_anterior"],
    "descripcion": "Ejercicio de aislamiento por excelencia para la cabeza lateral del hombro, otorgando amplitud y redondez.",
    "ejecucion_pasos": [
      "De pie con una mancuerna en cada mano a los costados y tronco ligeramente inclinado hacia adelante.",
      "Eleva los brazos hacia los lados en el plano escapular con codos con una flexión sutil.",
      "Sube hasta que los codos alcancen la altura de los hombros.",
      "Evita encoger el cuello para no activar en exceso el trapecio.",
      "Baja controladamente frenando la caída de las pesas."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["elevaciones-laterales-polea"],
    "precauciones": ["No usar balanceo de cadera para elevar el peso.", "Utilizar cargas moderadas con técnica estricta."],
    "tags": ["hombros", "deltoides_lateral", "aislamiento", "mancuernas"]
  },
  {
    "id": "elevaciones-laterales-polea",
    "nombre": "Elevaciones laterales en polea baja",
    "nombres_alternativos": ["Cable lateral raise"],
    "familia": "elevacion",
    "patron_movimiento": "elevacion",
    "zona": "superior",
    "musculos_principales": ["deltoides_lateral"],
    "musculos_secundarios": ["trapecio"],
    "descripcion": "Elevación lateral utilizando polea, manteniendo tensión mecánica desde el inicio del movimiento en contraste con las mancuernas.",
    "ejecucion_pasos": [
      "Coloca la polea en la posición más baja y colócate de lado a la torre.",
      "Toma el asa con la mano más alejada pasando el cable por detrás o por delante.",
      "Eleva el brazo lateralmente hasta la altura del hombro.",
      "Desciende despacio resistiendo la tracción del cable."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": true,
    "variantes": ["elevaciones-laterales-mancuernas"],
    "precauciones": ["Mantener el torso estable sin inclinarse para ayudar a la subida."],
    "tags": ["polea", "hombros", "deltoides_lateral", "aislamiento"]
  },
  {
    "id": "pajaros-posteriores-mancuernas",
    "nombre": "Pájaros con mancuernas",
    "nombres_alternativos": ["Rear delt flyes", "Elevaciones posteriores"],
    "familia": "elevacion",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["deltoides_posterior"],
    "musculos_secundarios": ["romboides", "trapecio"],
    "descripcion": "Ejercicio con el torso inclinado hacia adelante para aislar el haz posterior del deltoides y la musculatura escapular media.",
    "ejecucion_pasos": [
      "Inclina el torso hacia adelante en bisagra de cadera casi paralelo al suelo.",
      "Deja colgar las mancuernas bajo el pecho con codos levemente flexionados.",
      "Eleva los brazos hacia los lados y hacia atrás sintiendo el trabajo en la parte trasera del hombro.",
      "Baja con control sin balancear la espalda."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["face-pull-polea"],
    "precauciones": ["Mantener la columna recta y no elevar el torso al subir los brazos."],
    "tags": ["hombros", "deltoides_posterior", "mancuernas", "postura"]
  },
  {
    "id": "face-pull-polea",
    "nombre": "Face pull en polea",
    "nombres_alternativos": ["Jalón a la cara con cuerda"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["deltoides_posterior", "manguito_rotador"],
    "musculos_secundarios": ["trapecio", "romboides", "biceps_braquial"],
    "descripcion": "Tracción horizontal a la altura de la cara con rotación externa, esencial para la salud articular de los hombros y corrección postural.",
    "ejecucion_pasos": [
      "Coloca una cuerda en una polea alta a la altura de los ojos.",
      "Sujeta los extremos de la cuerda con agarre neutro o pulgares hacia atrás.",
      "Da un paso atrás y tracciona la cuerda hacia la cara separando las manos.",
      "Termina con las manos junto a las orejas y los codos altos en rotación externa.",
      "Aguanta un segundo retrayendo escápulas y regresa despacio."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["pajaros-posteriores-mancuernas"],
    "precauciones": ["No jalar hacia el pecho; la tracción debe ir hacia los ojos/frente."],
    "tags": ["salud_articular", "hombros", "deltoides_posterior", "polea", "postura"]
  },
  {
    "id": "press-frances-barra-z",
    "nombre": "Press francés con barra Z",
    "nombres_alternativos": ["Skull crushers", "Rompecráneos"],
    "familia": "extension_de_codo",
    "patron_movimiento": "extension_de_codo",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial"],
    "musculos_secundarios": ["antebrazos"],
    "descripcion": "Extensión de codos acostado en banco plano donde se desciende una barra Z hacia la frente o detrás de la coronilla.",
    "ejecucion_pasos": [
      "Túmbate en el banco sujetando la barra Z con agarre estrecho y brazos verticales.",
      "Flexiona únicamente los codos bajando la barra hacia la frente o ligeramente detrás de la cabeza.",
      "Los codos se mantienen fijos apuntando al techo sin abrirse hacia los lados.",
      "Extiende los codos contrayendo fuertemente los tríceps para regresar arriba."
    ],
    "equipamiento": ["barra", "banco", "discos"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["extension-triceps-polea-alta", "extension-triceps-tras-nuca-mancuerna"],
    "precauciones": ["No mover los hombros hacia adelante y atrás; aislar el codo.", "Controlar el peso para evitar impactos."],
    "tags": ["triceps", "aislamiento", "barra", "hipertrofia"]
  },
  {
    "id": "extension-triceps-polea-alta",
    "nombre": "Extensión de tríceps en polea alta",
    "nombres_alternativos": ["Triceps pushdown", "Jalón de tríceps con cuerda"],
    "familia": "extension_de_codo",
    "patron_movimiento": "extension_de_codo",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial"],
    "musculos_secundarios": ["antebrazos"],
    "descripcion": "Ejercicio clásico de aislamiento para tríceps empujando hacia abajo una cuerda o barra recta desde una polea alta.",
    "ejecucion_pasos": [
      "Colócate frente a la polea alta con los codos pegados a los costados.",
      "Toma la cuerda o barra y empuja hacia abajo extendiendo los codos.",
      "Al llegar abajo con cuerda, separa los extremos hacia afuera para máxima contracción.",
      "Sube controladamente hasta que los antebrazos superen los 90 grados sin mover los codos de su sitio."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-frances-barra-z", "extension-triceps-tras-nuca-polea"],
    "precauciones": ["No balancear el cuerpo hacia adelante ni usar inercia."],
    "tags": ["triceps", "polea", "aislamiento", "brazos"]
  },
  {
    "id": "extension-triceps-tras-nuca-mancuerna",
    "nombre": "Extensión de tríceps tras nuca con mancuerna",
    "nombres_alternativos": ["Overhead dumbbell triceps extension", "Copa de tríceps"],
    "familia": "extension_de_codo",
    "patron_movimiento": "extension_de_codo",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial"],
    "musculos_secundarios": [],
    "descripcion": "Extensión por encima de la cabeza que estira al máximo la cabeza larga del tríceps braquial.",
    "ejecucion_pasos": [
      "Siéntate o ponte de pie sosteniendo una mancuerna con ambas manos sobre la cabeza.",
      "Baja la mancuerna por detrás del cuello doblando los codos.",
      "Mantén los codos lo más cerrados posible apuntando hacia arriba.",
      "Extiende los brazos hacia el techo contrayendo los tríceps."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["press-frances-barra-z", "extension-triceps-tras-nuca-polea"],
    "precauciones": ["Cuidar la movilidad del hombro para no forzar la articulación."],
    "tags": ["triceps", "mancuernas", "cabeza_larga", "aislamiento"]
  },
  {
    "id": "extension-triceps-tras-nuca-polea",
    "nombre": "Extensión de tríceps tras nuca en polea",
    "nombres_alternativos": ["Overhead cable triceps extension"],
    "familia": "extension_de_codo",
    "patron_movimiento": "extension_de_codo",
    "zona": "superior",
    "musculos_principales": ["triceps_braquial"],
    "musculos_secundarios": [],
    "descripcion": "Extensión sobre la cabeza con polea que asegura tensión constante en la cabeza larga del tríceps.",
    "ejecucion_pasos": [
      "Ajusta la polea a media altura o alta y toma la cuerda dándole la espalda a la torre.",
      "Da un paso adelante con el torso inclinado y codos flexionados detrás de la cabeza.",
      "Extiende los brazos hacia adelante y arriba.",
      "Regresa despacio hasta el estiramiento completo."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["extension-triceps-tras-nuca-mancuerna", "extension-triceps-polea-alta"],
    "precauciones": ["Fijar la postura con los pies bien apoyados."],
    "tags": ["triceps", "polea", "brazos", "hipertrofia"]
  }
];
