export const upperPullExercises = [
  {
    "id": "remo-con-barra-inclinado",
    "nombre": "Remo con barra inclinado",
    "nombres_alternativos": ["Barbell bent-over row", "Remo 90 grados", "Remo con barra"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides", "trapecio"],
    "musculos_secundarios": ["biceps_braquial", "deltoides_posterior", "erectores_espinales"],
    "descripcion": "Ejercicio básico de tracción horizontal donde se tracciona una barra hacia el abdomen en posición de bisagra de cadera.",
    "ejecucion_pasos": [
      "Toma la barra con agarre prono un poco más ancho que los hombros.",
      "Inclina el torso hacia adelante en bisagra de cadera manteniendo la espalda recta.",
      "Deja colgar la barra con los brazos estirados.",
      "Tira de la barra hacia la parte baja del esternón o el ombligo llevando los codos hacia atrás.",
      "Aprieta las escápulas en el punto más alto.",
      "Baja la barra de forma controlada hasta la posición inicial."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["remo-pendlay", "remo-con-mancuerna-a-una-mano", "remo-en-polea-baja-gironda"],
    "precauciones": ["No balancear el torso bruscamente para subir la barra.", "Mantener la curvatura lumbar neutra para evitar sobrecargas."],
    "tags": ["espalda", "dorsal", "fuerza", "barra", "traccion"]
  },
  {
    "id": "remo-pendlay",
    "nombre": "Remo Pendlay",
    "nombres_alternativos": ["Pendlay row", "Remo estricto desde el suelo"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides", "trapecio"],
    "musculos_secundarios": ["biceps_braquial", "erectores_espinales", "deltoides_posterior"],
    "descripcion": "Variante estricta y explosiva de remo donde cada repetición se inicia desde el suelo con el torso completamente horizontal.",
    "ejecucion_pasos": [
      "Coloca la barra en el suelo y ubícate en bisagra de cadera con el torso paralelo al piso.",
      "Toma la barra con agarre prono firme.",
      "Tira de manera explosiva llevando la barra al pecho inferior sin mover el ángulo del torso.",
      "Regresa la barra hasta apoyarla completamente en el suelo.",
      "Detén el impulso antes de comenzar la siguiente repetición."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["remo-con-barra-inclinado"],
    "precauciones": ["No elevar el torso durante la tracción; debe mantenerse paralelo al suelo."],
    "tags": ["espalda", "potencia", "barra", "fuerza"]
  },
  {
    "id": "remo-con-mancuerna-a-una-mano",
    "nombre": "Remo con mancuerna a una mano",
    "nombres_alternativos": ["One-arm dumbbell row", "Remo serrucho", "Remo unilateral"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides"],
    "musculos_secundarios": ["biceps_braquial", "deltoides_posterior", "trapecio"],
    "descripcion": "Tracción unilateral apoyando una rodilla y mano sobre un banco, permitiendo un gran rango de movimiento y desarrollo equilibrado.",
    "ejecucion_pasos": [
      "Apoya una rodilla y una mano del mismo lado sobre un banco horizontal.",
      "Mantén la espalda plana paralela al banco y el otro pie firme en el suelo.",
      "Sujeta una mancuerna con la mano libre dejando colgar el brazo.",
      "Tira de la mancuerna hacia la cadera llevando el codo bien pegado al cuerpo.",
      "Contrae el dorsal en la parte superior y desciende sintiendo el estiramiento escapular.",
      "Completa las repeticiones y cambia de lado."
    ],
    "equipamiento": ["mancuernas", "banco"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["remo-con-barra-inclinado", "remo-en-polea-baja-gironda"],
    "precauciones": ["Evitar rotar excesivamente el torso al tirar de la mancuerna."],
    "tags": ["espalda", "dorsal", "unilateral", "mancuernas", "hipertrofia"]
  },
  {
    "id": "remo-en-polea-baja-gironda",
    "nombre": "Remo en polea baja sentado",
    "nombres_alternativos": ["Seated cable row", "Remo Gironda"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides", "trapecio"],
    "musculos_secundarios": ["biceps_braquial", "deltoides_posterior", "erectores_espinales"],
    "descripcion": "Remo sentado tirando de un maneral conectado a una polea baja con apoyo para los pies, garantizando tensión continua.",
    "ejecucion_pasos": [
      "Siéntate en la máquina apoyando los pies en los soportes con rodillas levemente flexionadas.",
      "Toma el maneral en V o barra y siéntate con el torso erguido.",
      "Tira del agarre hacia el abdomen retrayendo activamente las escápulas y sacando pecho.",
      "Mantén la contracción un segundo.",
      "Extiende los brazos lentamente dejando que las escápulas se abran sin encorvar la zona lumbar."
    ],
    "equipamiento": ["polea"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["remo-con-barra-inclinado", "remo-con-mancuerna-a-una-mano"],
    "precauciones": ["No balancear el torso hacia adelante y atrás para generar inercia."],
    "tags": ["polea", "espalda", "romboides", "dorsal", "principiante"]
  },
  {
    "id": "remo-t-con-apoyo-al-pecho",
    "nombre": "Remo en punta T con apoyo al pecho",
    "nombres_alternativos": ["Chest-supported T-bar row", "Remo T apoyado"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["romboides", "trapecio", "dorsal_ancho"],
    "musculos_secundarios": ["biceps_braquial", "deltoides_posterior"],
    "descripcion": "Remo en barra T con almohadilla en el pecho que descarga completamente la zona lumbar, permitiendo aislar la espalda alta.",
    "ejecucion_pasos": [
      "Apoya el pecho firmemente contra la almohadilla inclinada y asegura los pies.",
      "Sujeta los agarres con las palmas enfrentadas o en pronación.",
      "Tira de las manijas hacia ti retrayendo los omóplatos.",
      "Pausa en la cima y desciende lentamente hasta estirar los brazos."
    ],
    "equipamiento": ["maquina", "barra", "discos"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["remo-con-barra-inclinado", "remo-en-polea-baja-gironda"],
    "precauciones": ["No despegar el pecho del soporte durante el esfuerzo."],
    "tags": ["espalda_alta", "romboides", "espalda", "hipertrofia"]
  },
  {
    "id": "remo-invertido",
    "nombre": "Remo invertido",
    "nombres_alternativos": ["Inverted row", "Remo australiano"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides", "trapecio"],
    "musculos_secundarios": ["biceps_braquial", "recto_abdominal", "deltoides_posterior"],
    "descripcion": "Ejercicio de calistenia suspendido debajo de una barra o anillas tirando del pecho hacia la barra.",
    "ejecucion_pasos": [
      "Colócate debajo de una barra horizontal a la altura de la cintura.",
      "Toma la barra con agarre prono y extiende las piernas hacia adelante apoyando los talones.",
      "Mantén el cuerpo completamente recto en plancha invertida.",
      "Tira con la espalda y flexiona los brazos llevando el pecho a la barra.",
      "Baja de forma controlada hasta extender los brazos."
    ],
    "equipamiento": ["peso_corporal", "barra", "soporte_o_rack"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["remo-en-anillas", "dominadas-pronadas"],
    "precauciones": ["No dejar caer la pelvis; mantener glúteos activos."],
    "tags": ["calistenia", "peso_corporal", "espalda", "principiante"]
  },
  {
    "id": "remo-en-anillas",
    "nombre": "Remo en anillas",
    "nombres_alternativos": ["Ring rows", "Remo en suspensión"],
    "familia": "remo",
    "patron_movimiento": "traccion_horizontal",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "romboides"],
    "musculos_secundarios": ["biceps_braquial", "recto_abdominal", "deltoides_posterior"],
    "descripcion": "Remo con correas o anillas de suspensión que permite rotar las muñecas naturalmente durante el trayecto.",
    "ejecucion_pasos": [
      "Toma las anillas y camina con los pies adelante inclinando el cuerpo hacia atrás.",
      "Mantén el cuerpo recto y los brazos extendidos.",
      "Tira de las anillas hacia el pecho girando las muñecas a posición neutra.",
      "Regresa controlando el descenso."
    ],
    "equipamiento": ["anillas", "suspension", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["remo-invertido"],
    "precauciones": ["Ajustar el ángulo de inclinación para regular la dificultad."],
    "tags": ["anillas", "suspension", "calistenia", "espalda"]
  },
  {
    "id": "dominadas-pronadas",
    "nombre": "Dominadas con agarre prono",
    "nombres_alternativos": ["Pull-ups", "Dominadas abiertas"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho"],
    "musculos_secundarios": ["biceps_braquial", "braquial", "romboides", "trapecio", "recto_abdominal"],
    "descripcion": "Rey de los ejercicios de tracción vertical con peso corporal, colgándose de una barra con palmas hacia adelante y elevando el cuerpo hasta pasar la barbilla.",
    "ejecucion_pasos": [
      "Cuélgate de una barra con agarre prono algo más ancho que los hombros.",
      "Comienza desde suspensión completa con brazos rectos y escápulas activadas.",
      "Tracciona llevando los codos hacia las costillas y saca pecho.",
      "Sube hasta que la barbilla supere claramente la barra.",
      "Baja de forma controlada hasta la extensión completa de brazos."
    ],
    "equipamiento": ["barra_de_dominadas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["dominadas-supinadas", "dominadas-neutras", "jalon-al-pecho-polea"],
    "precauciones": ["Evitar balanceos excesivos de piernas (kipping) si se busca fuerza e hipertrofia estricta.", "Controlar la bajada para no dañar los hombros."],
    "tags": ["calistenia", "espalda", "dorsal", "fuerza", "peso_corporal"]
  },
  {
    "id": "dominadas-supinadas",
    "nombre": "Dominadas con agarre supino",
    "nombres_alternativos": ["Chin-ups", "Dominadas cerradas"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "biceps_braquial"],
    "musculos_secundarios": ["romboides", "pectoral_mayor"],
    "descripcion": "Dominadas con las palmas mirando hacia ti a la anchura de hombros, otorgando mayor ventaja mecánica y estímulo directo a los bíceps.",
    "ejecucion_pasos": [
      "Toma la barra con agarre supino (palmas hacia tu cara) al ancho de hombros.",
      "Desde suspensión completa, flexiona los brazos traccionando hacia arriba.",
      "Lleva el pecho hacia la barra superándola con el mentón.",
      "Desciende controladamente hasta estirar los brazos."
    ],
    "equipamiento": ["barra_de_dominadas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["dominadas-pronadas", "dominadas-neutras"],
    "precauciones": ["No encoger los hombros ni arquear excesivamente la espalda."],
    "tags": ["biceps", "espalda", "calistenia", "peso_corporal"]
  },
  {
    "id": "dominadas-neutras",
    "nombre": "Dominadas con agarre neutro",
    "nombres_alternativos": ["Neutral grip pull-ups"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "braquial", "biceps_braquial"],
    "musculos_secundarios": ["romboides", "trapecio"],
    "descripcion": "Dominadas con las palmas enfrentadas, la variante más ergonómica y cómoda para hombros, muñecas y codos.",
    "ejecucion_pasos": [
      "Sujeta los agarres paralelos con las palmas mirándose entre sí.",
      "Inicia el tirón desde posición colgada tirando de los codos hacia abajo.",
      "Eleva el pecho hasta la altura de las manos.",
      "Baja con suavidad y control."
    ],
    "equipamiento": ["barra_de_dominadas", "peso_corporal"],
    "tipo": "multiarticular",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["dominadas-pronadas", "dominadas-supinadas"],
    "precauciones": ["Mantener el rango completo de movimiento."],
    "tags": ["espalda", "braquial", "hombro_amigable", "calistenia"]
  },
  {
    "id": "jalon-al-pecho-polea",
    "nombre": "Jalón al pecho en polea alta",
    "nombres_alternativos": ["Lat pulldown", "Polea al pecho"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho"],
    "musculos_secundarios": ["biceps_braquial", "romboides", "deltoides_posterior"],
    "descripcion": "Tracción vertical sentado en máquina llevando una barra ancha hacia la parte alta del pecho, ideal para regular la carga de trabajo.",
    "ejecucion_pasos": [
      "Ajusta los rodillos para fijar bien los muslos y siéntate.",
      "Toma la barra ancha con agarre prono.",
      "Con el torso con una ligera inclinación hacia atrás de unos 10-15 grados, tira de la barra hacia la clavícula.",
      "Lleva los codos hacia las costillas apretando los dorsales.",
      "Retorna lentamente la barra hacia arriba estirando completamente los dorsales."
    ],
    "equipamiento": ["polea"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["dominadas-pronadas", "jalon-agarre-estrecho-polea"],
    "precauciones": ["Nunca jalar la barra detrás de la nuca para proteger la articulación glenohumeral y cervicales."],
    "tags": ["polea", "dorsal", "espalda", "principiante", "hipertrofia"]
  },
  {
    "id": "jalon-agarre-estrecho-polea",
    "nombre": "Jalón al pecho con agarre estrecho",
    "nombres_alternativos": ["Close-grip lat pulldown", "Jalón con maneral en V"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho"],
    "musculos_secundarios": ["biceps_braquial", "braquiorradial", "romboides"],
    "descripcion": "Jalón vertical utilizando un maneral cerrado en V, aumentando la aducción de codos y el estiramiento dorsal.",
    "ejecucion_pasos": [
      "Coloca el maneral en V en la polea alta y asegura tus piernas en el asiento.",
      "Toma el maneral e inclina el torso levemente hacia atrás sacando pecho.",
      "Tira del maneral hacia la parte media del pecho concentrándote en los codos.",
      "Aprieta en el punto bajo y regresa con control."
    ],
    "equipamiento": ["polea"],
    "tipo": "multiarticular",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["jalon-al-pecho-polea"],
    "precauciones": ["No balancear la espalda baja hacia atrás."],
    "tags": ["dorsal", "polea", "espalda", "brazos"]
  },
  {
    "id": "pull-over-en-polea-alta",
    "nombre": "Pull-over en polea alta con brazos rectos",
    "nombres_alternativos": ["Straight-arm cable pulldown", "Jalón con brazos rectos"],
    "familia": "dominada",
    "patron_movimiento": "traccion_vertical",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho"],
    "musculos_secundarios": ["triceps_braquial", "pectoral_mayor", "recto_abdominal"],
    "descripcion": "Ejercicio de aislamiento para el dorsal ancho que imita el movimiento de extensión de hombro sin participación de los flexores de codo.",
    "ejecucion_pasos": [
      "Colócate de pie frente a una polea alta con una barra recta o cuerda.",
      "Toma la barra con brazos extendidos y codos levemente desbloqueados.",
      "Inclina el torso 30 grados hacia adelante.",
      "Tracciona la barra hacia los muslos en un arco amplio utilizando únicamente los dorsales.",
      "Aprieta fuerte los dorsales abajo y sube lentamente sintiendo el estiramiento sobre la cabeza."
    ],
    "equipamiento": ["polea"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["jalon-al-pecho-polea"],
    "precauciones": ["No doblar los codos durante el trayecto para evitar la intervención del tríceps."],
    "tags": ["dorsal", "aislamiento", "polea", "espalda"]
  },
  {
    "id": "muscle-up",
    "nombre": "Muscle-up en barra",
    "nombres_alternativos": ["Musculación en barra", "Bar muscle-up"],
    "familia": "dominada",
    "patron_movimiento": "potencia",
    "zona": "superior",
    "musculos_principales": ["dorsal_ancho", "triceps_braquial", "pectoral_mayor"],
    "musculos_secundarios": ["biceps_braquial", "deltoides_anterior", "recto_abdominal"],
    "descripcion": "Movimiento avanzado de calistenia que combina una dominada explosiva alta con una rápida transición hacia un fondo sobre la barra.",
    "ejecucion_pasos": [
      "Cuélgate de la barra con agarre falso o prono firme.",
      "Genera una tracción explosiva llevando el pecho por encima de la barra.",
      "Rota rápidamente las muñecas y codos hacia adelante sobre la barra.",
      "Empuja hacia arriba en un fondo completo hasta extender los brazos.",
      "Baja con sumo cuidado repitiendo la trayectoria inversa."
    ],
    "equipamiento": ["barra_de_dominadas", "peso_corporal"],
    "tipo": "potencia",
    "nivel": "avanzado",
    "unilateral": false,
    "variantes": ["dominadas-pronadas", "fondos-en-paralelas"],
    "precauciones": ["Dominar previamente al menos 12-15 dominadas estrictas y fondos en barra antes de intentar."],
    "tags": ["calistenia", "avanzado", "potencia", "gimnasia"]
  },
  {
    "id": "curl-biceps-barra",
    "nombre": "Curl de bíceps con barra",
    "nombres_alternativos": ["Barbell curl", "Curl de bíceps de pie"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_codo",
    "zona": "superior",
    "musculos_principales": ["biceps_braquial"],
    "musculos_secundarios": ["braquial", "braquiorradial", "antebrazos"],
    "descripcion": "El clásico ejercicio de sobrecarga para flexores del codo de pie con barra recta o Z.",
    "ejecucion_pasos": [
      "Ponte de pie con pies al ancho de caderas y sujeta la barra con palmas hacia arriba al ancho de hombros.",
      "Pega los codos a los costados del torso y fija el abdomen.",
      "Flexiona los codos elevando la barra en un arco suave hacia el pecho.",
      "Contrae intensamente los bíceps arriba sin balancear la espalda.",
      "Desciende la barra controlando la fase excéntrica hasta la extensión casi total."
    ],
    "equipamiento": ["barra", "discos"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["curl-biceps-mancuernas-alterno", "curl-martillo-mancuernas", "curl-predicador-banco-scott"],
    "precauciones": ["No balancear el tronco ni arquear la zona lumbar para subir el peso."],
    "tags": ["biceps", "brazos", "barra", "fuerza", "hipertrofia"]
  },
  {
    "id": "curl-biceps-mancuernas-alterno",
    "nombre": "Curl de bíceps con mancuernas alterno",
    "nombres_alternativos": ["Alternate dumbbell curl", "Curl supino"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_codo",
    "zona": "superior",
    "musculos_principales": ["biceps_braquial"],
    "musculos_secundarios": ["braquial", "braquiorradial"],
    "descripcion": "Curl con mancuernas rotando la muñeca en supinación durante la flexión para activar plenamente la función supinadora del bíceps.",
    "ejecucion_pasos": [
      "Sostén una mancuerna en cada mano a los costados con palmas enfrentadas.",
      "Eleva una mancuerna girando la muñeca hacia afuera a medida que sube para que la palma mire hacia tu hombro arriba.",
      "Aprieta en la contracción y desciende lentamente.",
      "Repite con el otro brazo alternando repeticiones."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": true,
    "variantes": ["curl-biceps-barra", "curl-martillo-mancuernas"],
    "precauciones": ["Mantener los codos inmóviles pegados al cuerpo."],
    "tags": ["biceps", "mancuernas", "brazos", "hipertrofia"]
  },
  {
    "id": "curl-martillo-mancuernas",
    "nombre": "Curl martillo con mancuernas",
    "nombres_alternativos": ["Hammer curl", "Curl con agarre neutro"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_codo",
    "zona": "superior",
    "musculos_principales": ["braquial", "braquiorradial"],
    "musculos_secundarios": ["biceps_braquial", "antebrazos"],
    "descripcion": "Flexión de codos manteniendo las palmas enfrentadas (agarre neutro), desarrollando el músculo braquial anterior y los antebrazos.",
    "ejecucion_pasos": [
      "De pie o sentado con una mancuerna en cada mano y palmas apuntando hacia adentro.",
      "Flexiona los codos elevando las pesas sin rotar las muñecas, como martillando.",
      "Sube hasta la contracción máxima y desciende lentamente.",
      "Puede ejecutarse de forma simultánea o alterna."
    ],
    "equipamiento": ["mancuernas"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["curl-biceps-mancuernas-alterno", "curl-biceps-barra"],
    "precauciones": ["No adelantar los codos para acortar el recorrido."],
    "tags": ["antebrazo", "braquial", "biceps", "mancuernas"]
  },
  {
    "id": "curl-predicador-banco-scott",
    "nombre": "Curl predicador en banco Scott",
    "nombres_alternativos": ["Preacher curl", "Curl en banco Scott"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_codo",
    "zona": "superior",
    "musculos_principales": ["biceps_braquial"],
    "musculos_secundarios": ["braquial"],
    "descripcion": "Curl apoyando los brazos sobre un plano inclinado acolchado que impide cualquier tipo de trampa o inercia corporal.",
    "ejecucion_pasos": [
      "Siéntate ajustando la altura de modo que las axilas reposen sobre el borde superior de la almohadilla.",
      "Apoya la parte posterior de los brazos completamente en el plano.",
      "Toma la barra Z con agarre supino.",
      "Flexiona los brazos hacia la barbilla apretando en la cima.",
      "Baja con mucho control sin llegar a hiperextender bruscamente los codos abajo."
    ],
    "equipamiento": ["barra", "banco", "discos"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["curl-biceps-barra", "curl-spider-en-banco"],
    "precauciones": ["No rebotar en la parte más baja para proteger el tendón distal del bíceps."],
    "tags": ["biceps", "banco_scott", "aislamiento", "brazos"]
  },
  {
    "id": "curl-spider-en-banco",
    "nombre": "Spider curl en banco inclinado",
    "nombres_alternativos": ["Curl araña", "Spider curl"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_codo",
    "zona": "superior",
    "musculos_principales": ["biceps_braquial"],
    "musculos_secundarios": ["braquial"],
    "descripcion": "Curl acostado boca abajo sobre un banco inclinado con los brazos colgando perpendiculares al suelo, ofreciendo gran tensión en flexión.",
    "ejecucion_pasos": [
      "Apoya el pecho sobre un banco inclinado a unos 45 grados dejando colgar los brazos rectos hacia el suelo.",
      "Toma una barra Z o mancuernas con agarre supino.",
      "Flexiona los codos llevando el peso hacia la frente sin mover la parte superior del brazo.",
      "Aprieta en la cima y desciende lentamente."
    ],
    "equipamiento": ["mancuernas", "barra", "banco"],
    "tipo": "aislamiento",
    "nivel": "intermedio",
    "unilateral": false,
    "variantes": ["curl-predicador-banco-scott"],
    "precauciones": ["Mantener los brazos perpendiculares al suelo."],
    "tags": ["biceps", "aislamiento", "mancuernas", "pico_de_biceps"]
  },
  {
    "id": "curl-de-muneca-antebrazo",
    "nombre": "Curl de muñeca para antebrazo",
    "nombres_alternativos": ["Wrist curl", "Flexión de muñeca con barra"],
    "familia": "curl",
    "patron_movimiento": "flexion_de_muneca",
    "zona": "superior",
    "musculos_principales": ["antebrazos"],
    "musculos_secundarios": [],
    "descripcion": "Ejercicio de aislamiento para los flexores de muñeca y antebrazos apoyando los brazos sobre un banco.",
    "ejecucion_pasos": [
      "Arrodíllate frente a un banco y apoya los antebrazos sobre él dejando las muñecas colgando por el borde con palmas hacia arriba.",
      "Sujeta una barra ligera con los dedos.",
      "Flexiona las muñecas elevando la barra hacia ti.",
      "Baja la barra lentamente permitiendo que ruede ligeramente por los dedos para máximo estiramiento."
    ],
    "equipamiento": ["barra", "discos", "banco"],
    "tipo": "aislamiento",
    "nivel": "principiante",
    "unilateral": false,
    "variantes": ["curl-martillo-mancuernas"],
    "precauciones": ["Utilizar cargas ligeras para proteger los tendones flexores de la muñeca."],
    "tags": ["antebrazo", "agarre", "aislamiento"]
  }
];
