import fs from 'fs';
import path from 'path';

/**
 * Script de Normalización del Catálogo Maestro — Punto 3C
 * Aplica el Marco Biomecánico de Referencia (3A) y la Taxonomía Oficial (3B)
 * a los 109 ejercicios oficiales en src/data/ejercicios.json.
 */

const CANONICAL_PATH = path.resolve('src', 'data', 'ejercicios.json');

// Mapeo exhaustivo de los 109 ejercicios con sus variables biomecánicas y taxonómicas normalizadas
export const NORMALIZED_PROFILES = {
  // --- 1. GRUPO SENTADILLAS ---
  'sentadilla': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'soporte_o_rack', 'disco'],
    estabilizadores: ['erectores_espinales', 'transverso_abdominal', 'recto_abdominal']
  },
  'sentadilla-frontal': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral', 'escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'soporte_o_rack', 'disco'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales', 'deltoides_anterior']
  },
  'sentadilla-goblet': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'kettlebell'],
    estabilizadores: ['recto_abdominal', 'biceps_braquial', 'erectores_espinales']
  },
  'sentadilla-sumo': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'mancuerna', 'kettlebell', 'disco'],
    estabilizadores: ['erectores_espinales', 'transverso_abdominal']
  },
  'sentadilla-bulgara': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['banco', 'mancuerna', 'peso_corporal'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal', 'erectores_espinales']
  },
  'sentadilla-aerea': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },
  'sentadilla-pistola': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['gluteo_medio', 'tibial_anterior', 'recto_abdominal']
  },
  'prensa-de-piernas': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina', 'disco'],
    estabilizadores: ['recto_abdominal']
  },
  'sentadilla-hack': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina', 'disco'],
    estabilizadores: ['recto_abdominal']
  },
  'sentadilla-isometrica-pared': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'sentadilla',
    familia: 'sentadilla',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal']
  },

  // --- 2. GRUPO PESO MUERTO Y BISAGRA DE CADERA ---
  'peso-muerto-convencional': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['columna_vertebral', 'tobillo', 'escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'trapecio', 'dorsal_ancho', 'recto_abdominal']
  },
  'peso-muerto-sumo': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['columna_vertebral', 'tobillo', 'escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'trapecio', 'transverso_abdominal']
  },
  'peso-muerto-rumano-barra': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'dorsal_ancho', 'recto_abdominal']
  },
  'peso-muerto-rumano-mancuernas': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['erectores_espinales', 'dorsal_ancho', 'recto_abdominal']
  },
  'peso-muerto-unilateral': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'kettlebell', 'peso_corporal'],
    estabilizadores: ['gluteo_medio', 'erectores_espinales', 'recto_abdominal']
  },
  'hip-thrust-barra': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'banco', 'disco'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },
  'hip-thrust-unilateral': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['banco', 'mancuerna', 'peso_corporal'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal']
  },
  'puente-de-gluteos': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },
  'buenos-dias': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'bisagra_de_cadera',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'transverso_abdominal']
  },
  'kettlebell-swing': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'bisagra_de_cadera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'hombro', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'potencia',
    equipamiento: ['kettlebell'],
    estabilizadores: ['erectores_espinales', 'dorsal_ancho', 'recto_abdominal']
  },

  // --- 3. GRUPO ZANCADAS Y LOCOMOCIÓN INFERIOR ---
  'zancadas-caminando': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'zancada',
    familia: 'zancada',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'peso_corporal', 'barra'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal']
  },
  'zancadas-estaticas': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'zancada',
    familia: 'zancada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'peso_corporal', 'barra'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal']
  },
  'zancadas-inversas': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'zancada',
    familia: 'zancada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'peso_corporal', 'kettlebell'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal']
  },
  'step-up-banco': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'locomocion',
    familia: 'zancada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla'],
    articulaciones_secundarias: ['tobillo'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['banco', 'cajon', 'mancuerna', 'peso_corporal'],
    estabilizadores: ['gluteo_medio', 'recto_abdominal']
  },

  // --- 4. AISLAMIENTO TREN INFERIOR ---
  'extension-cuadriceps-maquina': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_rodilla',
    familia: 'extension_de_piernas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['rodilla'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: []
  },
  'curl-femoral-tumbado': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_rodilla',
    familia: 'flexion_de_piernas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['rodilla'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: ['gemelos']
  },
  'curl-femoral-sentado': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_rodilla',
    familia: 'flexion_de_piernas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['rodilla'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: ['gemelos']
  },
  'curl-nordico': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'flexion_de_rodilla',
    familia: 'flexion_de_piernas',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['rodilla'],
    articulaciones_secundarias: ['cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['gluteo_mayor', 'erectores_espinales', 'recto_abdominal']
  },
  'elevacion-talones-de-pie': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_tobillo',
    familia: 'elevacion',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['tobillo'],
    articulaciones_secundarias: ['rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina', 'mancuerna', 'peso_corporal'],
    estabilizadores: ['tibial_anterior']
  },
  'elevacion-talones-sentado': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_tobillo',
    familia: 'elevacion',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['tobillo'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: []
  },

  // --- 5. EMPUJE HORIZONTAL TREN SUPERIOR ---
  'press-banca-plano-barra': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'banco', 'soporte_o_rack', 'disco'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior', 'romboides']
  },
  'press-banca-inclinado-barra': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'banco', 'soporte_o_rack', 'disco'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior']
  },
  'press-banca-declinado-barra': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'banco', 'soporte_o_rack', 'disco'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior']
  },
  'press-banca-plano-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior']
  },
  'press-banca-inclinado-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior']
  },
  'press-pecho-maquina': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: ['manguito_rotador']
  },
  'flexiones-de-brazos': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'serrato_anterior', 'erectores_espinales']
  },
  'flexiones-diamante': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['codo', 'hombro'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'serrato_anterior']
  },
  'flexiones-declinadas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal', 'banco'],
    estabilizadores: ['recto_abdominal', 'serrato_anterior']
  },
  'flexiones-arqueras': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_horizontal',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'serrato_anterior', 'gluteo_mayor']
  },

  // --- 6. EMPUJE VERTICAL TREN SUPERIOR ---
  'fondos-en-paralelas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['paralelas', 'peso_corporal'],
    estabilizadores: ['romboides', 'serrato_anterior', 'recto_abdominal']
  },
  'fondos-en-banco': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['codo', 'hombro'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['banco', 'peso_corporal'],
    estabilizadores: ['romboides']
  },
  'fondos-en-anillas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['anillas', 'suspension', 'peso_corporal'],
    estabilizadores: ['manguito_rotador', 'serrato_anterior', 'recto_abdominal']
  },
  'press-militar-barra': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra', 'disco', 'soporte_o_rack'],
    estabilizadores: ['recto_abdominal', 'gluteo_mayor', 'erectores_espinales']
  },
  'press-hombros-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['manguito_rotador', 'trapecio']
  },
  'press-arnold': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'multiplanar',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['manguito_rotador', 'trapecio']
  },
  'push-press': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'press',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['hombro', 'codo', 'rodilla', 'cadera'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'recto_abdominal']
  },
  'flexiones-hspu': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales', 'serrato_anterior']
  },
  'pike-push-ups': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_vertical',
    familia: 'press',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'serrato_anterior']
  },

  // --- 7. AISLAMIENTO EMPUJE Y HOMBRO ---
  'aperturas-mancuernas-plano': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'aperturas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['codo'],
    plano_predominante: 'transversal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['biceps_braquial', 'manguito_rotador']
  },
  'cruce-de-poleas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'aperturas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['codo'],
    plano_predominante: 'transversal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },
  'contractora-pec-deck': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'empuje_horizontal',
    familia: 'aperturas',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: [],
    plano_predominante: 'transversal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina'],
    estabilizadores: []
  },
  'elevaciones-laterales-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'abduccion_de_hombro',
    familia: 'elevacion',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'frontal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['trapecio', 'recto_abdominal']
  },
  'elevaciones-laterales-polea': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'abduccion_de_hombro',
    familia: 'elevacion',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'frontal',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['oblicuo_externo']
  },
  'pajaros-posteriores-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'elevacion',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'transversal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['erectores_espinales']
  },
  'face-pull-polea': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica', 'codo'],
    plano_predominante: 'transversal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'salud_articular',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },

  // --- 8. EXTENSIONES DE TRÍCEPS ---
  'press-frances-barra-z': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_codo',
    familia: 'extension_de_codo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'banco', 'disco'],
    estabilizadores: ['manguito_rotador']
  },
  'extension-triceps-polea-alta': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_codo',
    familia: 'extension_de_codo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },
  'extension-triceps-tras-nuca-mancuerna': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_codo',
    familia: 'extension_de_codo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['recto_abdominal']
  },
  'extension-triceps-tras-nuca-polea': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'extension_de_codo',
    familia: 'extension_de_codo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },

  // --- 9. TRACCIÓN HORIZONTAL (REMOS) ---
  'remo-con-barra-inclinado': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'cadera', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'isquiotibiales', 'recto_abdominal']
  },
  'remo-pendlay': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'cadera', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'isquiotibiales', 'gluteo_mayor']
  },
  'remo-con-mancuerna-a-una-mano': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'banco'],
    estabilizadores: ['oblicuo_externo', 'erectores_espinales']
  },
  'remo-en-polea-baja-gironda': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['erectores_espinales']
  },
  'remo-t-con-apoyo-al-pecho': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['maquina', 'barra', 'disco'],
    estabilizadores: []
  },
  'remo-invertido': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal', 'barra', 'soporte_o_rack'],
    estabilizadores: ['gluteo_mayor', 'erectores_espinales', 'recto_abdominal']
  },
  'remo-en-anillas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_horizontal',
    familia: 'remo',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'hipertrofia',
    equipamiento: ['anillas', 'suspension', 'peso_corporal'],
    estabilizadores: ['manguito_rotador', 'gluteo_mayor', 'recto_abdominal']
  },

  // --- 10. TRACCIÓN VERTICAL (DOMINADAS Y JALONES) ---
  'dominadas-pronadas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'frontal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra_de_dominadas', 'peso_corporal'],
    estabilizadores: ['recto_abdominal', 'romboides', 'trapecio']
  },
  'dominadas-supinadas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra_de_dominadas', 'peso_corporal'],
    estabilizadores: ['recto_abdominal', 'romboides']
  },
  'dominadas-neutras': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'fuerza',
    equipamiento: ['barra_de_dominadas', 'peso_corporal'],
    estabilizadores: ['recto_abdominal', 'romboides']
  },
  'jalon-al-pecho-polea': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'frontal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },
  'jalon-agarre-estrecho-polea': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal']
  },
  'pull-over-en-polea-alta': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'traccion_vertical',
    familia: 'dominada',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['recto_abdominal', 'triceps_braquial']
  },
  'muscle-up': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'dominada',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'codo'],
    articulaciones_secundarias: ['escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra_de_dominadas', 'peso_corporal'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },

  // --- 11. AISLAMIENTO BRAZOS (BÍCEPS Y ANTEBRAZO) ---
  'curl-biceps-barra': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_codo',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['deltoides_anterior', 'recto_abdominal']
  },
  'curl-biceps-mancuernas-alterno': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_codo',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['oblicuo_externo']
  },
  'curl-martillo-mancuernas': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_codo',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: ['muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna'],
    estabilizadores: ['deltoides_anterior']
  },
  'curl-predicador-banco-scott': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_codo',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'banco', 'disco'],
    estabilizadores: []
  },
  'curl-spider-en-banco': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_codo',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['codo'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['mancuerna', 'barra', 'banco'],
    estabilizadores: []
  },
  'curl-de-muneca-antebrazo': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_muneca',
    familia: 'curl',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['muneca'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['barra', 'disco', 'banco'],
    estabilizadores: []
  },

  // --- 12. CORE ---
  'plancha-abdominal-frontal': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_extension',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['hombro', 'cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['serrato_anterior', 'gluteo_mayor', 'cuadriceps']
  },
  'plancha-lateral': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_flexion_lateral',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['hombro', 'cadera'],
    plano_predominante: 'frontal',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['gluteo_medio', 'serrato_anterior']
  },
  'rueda-abdominal': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'anti_extension',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral', 'hombro'],
    articulaciones_secundarias: ['cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['rueda_abdominal', 'esterilla'],
    estabilizadores: ['dorsal_ancho', 'serrato_anterior', 'gluteo_mayor']
  },
  'hollow-body-hold': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_extension',
    familia: 'core',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['cadera', 'hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'resistencia',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['iliopsoas', 'cuadriceps']
  },
  'elevacion-piernas-colgado': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'flexion_de_cadera',
    familia: 'core',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['cadera', 'columna_vertebral'],
    articulaciones_secundarias: ['hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['barra_de_dominadas', 'peso_corporal'],
    estabilizadores: ['dorsal_ancho', 'antebrazos']
  },
  'crunch-abdominal-suelo': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_tronco',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: [],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: []
  },
  'crunch-en-polea-alta': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'hipertrofia',
    patron_movimiento: 'flexion_de_tronco',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'baja',
    objetivo: 'hipertrofia',
    equipamiento: ['polea'],
    estabilizadores: ['serrato_anterior']
  },
  'dead-bug': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_extension',
    familia: 'core',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['hombro', 'cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'salud_articular',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['transverso_abdominal', 'oblicuo_interno']
  },
  'bird-dog': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_rotacion',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['hombro', 'cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'salud_articular',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['erectores_espinales', 'gluteo_medio', 'transverso_abdominal']
  },
  'press-pallof': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'anti_rotacion',
    familia: 'core',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['hombro', 'codo'],
    plano_predominante: 'transversal',
    unilateralidad: 'asimetrico',
    unilateral: true,
    tipo_resistencia: 'polea',
    demanda_estabilidad: 'media',
    objetivo: 'salud_articular',
    equipamiento: ['polea', 'banda_elastica'],
    estabilizadores: ['gluteo_medio', 'deltoides_anterior']
  },
  'giros-rusos': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'rotacion',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['cadera'],
    plano_predominante: 'transversal',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'resistencia',
    equipamiento: ['disco', 'mancuerna', 'peso_corporal', 'esterilla'],
    estabilizadores: ['iliopsoas', 'recto_abdominal']
  },

  // --- 13. POTENCIA Y LEVANTAMIENTOS OLÍMPICOS ---
  'cargada-de-potencia': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'potencia',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo', 'hombro', 'codo'],
    articulaciones_secundarias: ['columna_vertebral', 'escapulo_toracica', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'trapecio', 'recto_abdominal']
  },
  'dos-tiempos-clean-and-jerk': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'potencia',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo', 'hombro', 'codo'],
    articulaciones_secundarias: ['columna_vertebral', 'escapulo_toracica', 'muneca'],
    plano_predominante: 'multiplanar',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra', 'disco'],
    musculos_secundarios: ['recto_abdominal', 'erectores_espinales', 'isquiotibiales', 'antebrazos'],
    estabilizadores: ['erectores_espinales', 'recto_abdominal', 'trapecio', 'gluteo_medio']
  },
  'arrancada-snatch': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'potencia',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo', 'hombro', 'codo'],
    articulaciones_secundarias: ['columna_vertebral', 'escapulo_toracica', 'muneca'],
    plano_predominante: 'multiplanar',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'potencia',
    equipamiento: ['barra', 'disco'],
    estabilizadores: ['erectores_espinales', 'recto_abdominal', 'trapecio', 'manguito_rotador']
  },
  'salto-al-cajon': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'salto',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['tobillo', 'rodilla', 'cadera'],
    articulaciones_secundarias: ['columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'potencia',
    equipamiento: ['cajon'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },
  'lanzamiento-balon-al-suelo': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'potencia',
    patron_movimiento: 'potencia',
    familia: 'potencia',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro', 'columna_vertebral', 'cadera'],
    articulaciones_secundarias: ['codo', 'rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'potencia',
    equipamiento: ['balon_medicinal'],
    estabilizadores: ['recto_abdominal', 'dorsal_ancho']
  },

  // --- 14. TRANSPORTE Y CONDICIÓN FUNCIONAL ---
  'paseo-del-granjero': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'locomocion',
    familia: 'transporte',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo'],
    articulaciones_secundarias: ['escapulo_toracica', 'columna_vertebral', 'muneca'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'fuerza',
    equipamiento: ['mancuerna', 'kettlebell', 'disco'],
    estabilizadores: ['trapecio', 'recto_abdominal', 'oblicuo_externo', 'erectores_espinales']
  },
  'empuje-de-trineo': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'resistencia_muscular',
    patron_movimiento: 'locomocion',
    familia: 'transporte',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo'],
    articulaciones_secundarias: ['hombro', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'media',
    objetivo: 'acondicionamiento',
    equipamiento: ['trineo', 'disco'],
    estabilizadores: ['recto_abdominal', 'pantorrillas', 'deltoides_anterior']
  },
  'burpees': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'locomocion',
    familia: 'carrera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'rodilla', 'tobillo', 'hombro', 'codo'],
    articulaciones_secundarias: ['columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'acondicionamiento',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'erectores_espinales']
  },
  'mountain-climbers': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'flexion_de_cadera',
    familia: 'core',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['rodilla', 'hombro', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'acondicionamiento',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal', 'deltoides_anterior', 'serrato_anterior']
  },
  'levantamiento-turco': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'fuerza',
    patron_movimiento: 'locomocion',
    familia: 'movilidad',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['hombro', 'cadera', 'rodilla', 'columna_vertebral'],
    articulaciones_secundarias: ['escapulo_toracica', 'tobillo'],
    plano_predominante: 'multiplanar',
    unilateralidad: 'unilateral',
    unilateral: true,
    tipo_resistencia: 'peso_libre',
    demanda_estabilidad: 'alta',
    objetivo: 'salud_articular',
    equipamiento: ['kettlebell', 'mancuerna', 'esterilla'],
    estabilizadores: ['manguito_rotador', 'recto_abdominal', 'oblicuo_externo', 'gluteo_medio']
  },

  // --- 15. CARDIOVASCULAR Y LOCOMOCIÓN CÍCLICA ---
  'saltos-con-cuerda': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'locomocion',
    familia: 'carrera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['tobillo', 'rodilla'],
    articulaciones_secundarias: ['muneca', 'hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'acondicionamiento',
    equipamiento: ['cuerda'],
    estabilizadores: ['recto_abdominal', 'soleo', 'gemelos']
  },
  'saltos-en-tijera': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'locomocion',
    familia: 'carrera',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera', 'hombro', 'tobillo'],
    articulaciones_secundarias: ['rodilla'],
    plano_predominante: 'frontal',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'acondicionamiento',
    equipamiento: ['peso_corporal'],
    estabilizadores: ['recto_abdominal']
  },
  'remoergometro': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'locomocion',
    familia: 'carrera',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['rodilla', 'cadera', 'hombro', 'codo'],
    articulaciones_secundarias: ['tobillo', 'columna_vertebral'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'baja',
    objetivo: 'acondicionamiento',
    equipamiento: ['maquina'],
    estabilizadores: ['erectores_espinales', 'recto_abdominal']
  },
  'carrera-en-cinta': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'cardiovascular',
    patron_movimiento: 'locomocion',
    familia: 'carrera',
    cadena_cinetica: 'mixta',
    articulaciones_principales: ['tobillo', 'rodilla', 'cadera'],
    articulaciones_secundarias: ['columna_vertebral', 'hombro'],
    plano_predominante: 'sagital',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'maquina_guiada',
    demanda_estabilidad: 'media',
    objetivo: 'acondicionamiento',
    equipamiento: ['maquina'],
    estabilizadores: ['recto_abdominal', 'gluteo_medio']
  },

  // --- 16. MOVILIDAD ARTICULAR ---
  'gato-camello': {
    zona: 'core',
    zona_anatomica: 'core',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'movilidad',
    patron_movimiento: 'movilidad',
    familia: 'movilidad',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['columna_vertebral'],
    articulaciones_secundarias: ['escapulo_toracica', 'cadera'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'salud_articular',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['transverso_abdominal']
  },
  'rotacion-de-cadera-90-90': {
    zona: 'inferior',
    zona_anatomica: 'inferior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'movilidad',
    patron_movimiento: 'movilidad',
    familia: 'movilidad',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['cadera'],
    articulaciones_secundarias: ['pelvis'],
    plano_predominante: 'transversal',
    unilateralidad: 'alternado',
    unilateral: true,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'baja',
    objetivo: 'salud_articular',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['gluteo_medio', 'oblicuo_interno']
  },
  'perro-boca-abajo': {
    zona: 'cuerpo_completo',
    zona_anatomica: 'cuerpo_completo',
    tipo: 'multiarticular',
    tipo_ejercicio: 'multiarticular',
    capacidad_fisica: 'movilidad',
    patron_movimiento: 'movilidad',
    familia: 'movilidad',
    cadena_cinetica: 'cerrada',
    articulaciones_principales: ['hombro', 'cadera', 'tobillo', 'columna_vertebral'],
    articulaciones_secundarias: ['escapulo_toracica', 'rodilla'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'peso_corporal',
    demanda_estabilidad: 'media',
    objetivo: 'salud_articular',
    equipamiento: ['peso_corporal', 'esterilla'],
    estabilizadores: ['serrato_anterior', 'recto_abdominal']
  },
  'dislocaciones-de-hombro-con-banda': {
    zona: 'superior',
    zona_anatomica: 'superior',
    tipo: 'aislamiento',
    tipo_ejercicio: 'aislamiento',
    capacidad_fisica: 'movilidad',
    patron_movimiento: 'movilidad',
    familia: 'movilidad',
    cadena_cinetica: 'abierta',
    articulaciones_principales: ['hombro'],
    articulaciones_secundarias: ['escapulo_toracica', 'codo'],
    plano_predominante: 'sagital',
    unilateralidad: 'bilateral',
    unilateral: false,
    tipo_resistencia: 'elastico',
    demanda_estabilidad: 'baja',
    objetivo: 'salud_articular',
    equipamiento: ['banda_elastica'],
    estabilizadores: ['trapecio', 'romboides']
  }
};

export function runNormalization() {
  console.log('Iniciando normalización del Catálogo Maestro...');
  const raw = fs.readFileSync(CANONICAL_PATH, 'utf-8');
  const catalog = JSON.parse(raw);
  const exercises = catalog.ejercicios;

  console.log(`Ejercicios cargados: ${exercises.length}`);
  if (exercises.length !== 109) {
    throw new Error(`Se esperaban 109 ejercicios, encontrados: ${exercises.length}`);
  }

  let modifiedCount = 0;
  const changeLog = [];

  exercises.forEach((ex, idx) => {
    const profile = NORMALIZED_PROFILES[ex.id];
    if (!profile) {
      throw new Error(`Ejercicio no encontrado en perfiles normalizados: ${ex.id}`);
    }

    const before = {
      zona: ex.zona,
      tipo: ex.tipo,
      patron_movimiento: ex.patron_movimiento,
      familia: ex.familia,
      equipamiento: [...(ex.equipamiento || [])]
    };

    // Aplicar campos normalizados
    Object.assign(ex, profile);

    // Si hubo cambios semánticos relevantes, registrar
    const hasChanges = (
      before.zona !== ex.zona ||
      before.tipo !== ex.tipo ||
      before.patron_movimiento !== ex.patron_movimiento ||
      before.familia !== ex.familia ||
      JSON.stringify(before.equipamiento) !== JSON.stringify(ex.equipamiento)
    );

    if (hasChanges) {
      modifiedCount++;
      changeLog.push({
        id: ex.id,
        nombre: ex.nombre,
        cambios: {
          zona: { anterior: before.zona, nuevo: ex.zona },
          tipo: { anterior: before.tipo, nuevo: ex.tipo },
          patron: { anterior: before.patron_movimiento, nuevo: ex.patron_movimiento },
          familia: { anterior: before.familia, nuevo: ex.familia },
          equipamiento: { anterior: before.equipamiento, nuevo: ex.equipamiento }
        }
      });
    }
  });

  // Actualizar metadatos del catálogo conservando la versión activa
  if (!catalog.version || catalog.version < '1.3.0') {
    catalog.version = '1.3.0';
    catalog.schema_version = '1.3';
  }
  catalog.descripcion = 'Catálogo maestro oficial y fuente canónica normalizada con perfiles biomecánicos de referencia (3A/3B/3C)';

  // Guardar archivo canónico
  fs.writeFileSync(CANONICAL_PATH, JSON.stringify(catalog, null, 2), 'utf-8');
  console.log(`✔ Normalización completada con éxito. ${modifiedCount} ejercicios adaptados a la taxonomía.`);

  return { catalog, modifiedCount, changeLog };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve('scripts/normalizeCatalog.js');
if (isMain) {
  const res = runNormalization();
  console.log(`Total modificaciones conceptuales registradas: ${res.modifiedCount}`);
}
